### ISSUE TITLE
Attempts to block user

### ISSUE THREAD

**Issue by bugada** [PHPAuth/PHPAuth#101]
1)The number of attempts used to block user should be taken from configuration, currently is fixed to 5. A value of -1 can mean blocking disabled.

2)The addAttempts() function is called on every error situation, this leads to block users too easily.
E.g.: the user inserts three times the wrong password, then asks for a reset password: if the user don't receive the email in a short time, probably he asks for another reset, incrementing the count. After that he is blocked even if he has the reset key.

**Comment by Conver** [comment]
See: 34cc077ccd7bf4fde18f6efd27ace99326127698

**Comment by bugada** [comment]
Thank you, my fault.
