### ISSUE TITLE
Two Factor Authentication / Authy 

### ISSUE THREAD

**Issue by Conver** [PHPAuth/PHPAuth#102]
Two Factor Authentication would be a good thing to have, but should it be a plugin or in the core class?

see: https://github.com/PHPGangsta/GoogleAuthenticator

Same goes for Authy 
https://github.com/authy/authy-php

**Comment by KarelWintersky** [comment]
It think, it must be plugin class.

**Comment by Conver** [comment]
I think it should be an plugin too

**Comment by Conver** [comment]
see #413
