### ISSUE TITLE
Inefficent count system

### ISSUE THREAD

**Issue by bugada** [PHPAuth/PHPAuth#106]
In isMailTaken() and isBlocked() the query does a 'select field from' and then $query->rowCount() instead of select count(). This is ok when we use the fetched fields, not very efficient when counting:
using count(), internally the db engine will process the request differently and will only allocate memory to store the result of the count.
When using $query->rowCount(); the server (Apache/PHP) will process the entire result set, allocate memory for all those results, and put the server in fetching mode, which involves a lot of different details, such as locking. 

Can I change these queries or there is a reason for the  $query->rowCount() approach?

**Comment by Conver** [comment]
No reason. Feel free to submit PR

**Comment by KarelWintersky** [comment]
:+1:

**Comment by bugada** [comment]
Fixed with #111
