### ISSUE TITLE
Testing

### ISSUE THREAD

**Issue by JacquesLoubser** [PHPAuth/PHPAuth#110]
Since it is quite difficult to test this library by hand, I suggest setting up some type of testing (maybe PHPUnit/Travis-CI?) to make it possible to locate any issues.

**Comment by bugada** [comment]
I agree.

**Comment by Conver** [comment]
Added Travis-CI, anyone with some knowledge on how it works?

https://travis-ci.org/PHPAuth/PHPAuth

**Comment by JacquesLoubser** [comment]
I do not.
But what I could find is that the testing will take place in PHPUnit and Travis-CI will do the continuous bit. 
The Beginners' Guide on the Travis-CI website is an example of using Travis-CI and PHPUnit to test an example repository. That should give us a start http://docs.travis-ci.com/user/for-beginners/
We will also need a database setup http://docs.travis-ci.com/user/database-setup/
I'll try to mess around with it and maybe something works.

**Comment by Conver** [comment]
Thanks @JacquesLoubser

**Comment by JacquesLoubser** [comment]
Update: .travis.yml working 100% with sample test, but I can't get the Database file to load on before-script. Will continue looking for answers.

**Comment by Conver** [comment]
I'll so some research too. Can you paste me the working one you have so far?

**Comment by JacquesLoubser** [comment]
It is quite modified to force the correct error. I'll go through my history and find something that makes sense. I need a one liner to import a SQL file to a database. I thought of just doing it in PHP. I will post it tomorrow (my git PC is very busy)

**Comment by JacquesLoubser** [comment]
@Conver check out https://github.com/JacquesLoubser/travis-broken-example
I have been trying to get everything right in this repository. Basically, the unit test creates and instance of the super class and runs the go() method, which checks for existence of the testdb database. The before-script command in .travis.yml is the one that creates the DB, and is not working. I have tried several Copy-Paste solutions from around the web with no luck. The user is 'root' and the password is blank.

**Comment by cuonic** [comment]
I'm working on the PHPUnit tests, I'm not sure if I'm doing things correctly but it's a start. I'll push soon.
