### ISSUE TITLE
Expiration date

### ISSUE THREAD

**Issue by dvdvgo** [PHPAuth/PHPAuth#123]
It would be great to add "expiration" in the db.config table instead of a "+1 day" default option. 

> $expire = date("Y-m-d H:i:s", strtotime("+1 day"));

**Comment by bugada** [comment]
Yes, I agree

**Comment by Conver** [comment]
You'll have to clarify this some more.. Not sure I follow you.

**Comment by bugada** [comment]
When we add a request after a reset password or registration, the expire time of the request is hardcoded

$expire = date("Y-m-d H:i:s", strtotime("+1 day"));  (line 723)

@dvdvgo suggested configuring in the configuration a take the value from there

**Comment by bugada** [comment]
I'll manage it in my next free time :smile:

**Comment by Conver** [comment]
I follow.. not sure if I'm going to accept a PR for that.

I don't see a reason for why it should be in the DB. Those that are hardcoded should never last more than 1 day.

Give me a few use cases where you want an activation key or password reset to last more than 1 day?.. never, right?

**Comment by bugada** [comment]
More that 1 day but also less than 1 day: usually this is a committent request, one of them asked me for a 168 hours expiration. Others want half an hour. I have to modify the class and upgrade is a pain.

**Comment by KarelWintersky** [comment]
May be `+86400 seconds` will be better? :)

**Comment by bugada** [comment]
:) :)

**Comment by Conver** [comment]
@bugada, feel free to submit PR

**Comment by cuonic** [comment]
Issue #128 is relevant to this, one of the solutions would be to change the expiration date of password reset emails (I'm proposing `+10 minutes` to solve the problem). Making this configurable will keep everyone happy and make PHPAuth adaptable to all use cases.

**Comment by bugada** [comment]
Ok @cuonic I'll do it asap :-)
