### ISSUE TITLE
Get current UID?

### ISSUE THREAD

**Issue by MrPurplz** [PHPAuth/PHPAuth#125]
I apologise for the newbie question but I cannot for the life of me work out how to get the logged in sessions UID.

I've found getUID() but that requires the email to get it.

And getSessionUID() requires a $hash

But getHash() says it 'Hashes a given string with the provided salt using bcrypt' which doesn't seem to be what I'm looking for.

How do I get either the email or UID of the currently logged in user?

**Comment by bugada** [comment]
Get the user object like that

$user = $auth->getUser($auth->getSessionUID($auth->getSessionHash()));

Then you can get all user properties (except for puser password).

**Comment by MrPurplz** [comment]
Perfect, thank you
