### ISSUE TITLE
[Suggestion] Releases and Versioning

### ISSUE THREAD

**Issue by livmackintosh** [PHPAuth/PHPAuth#132]
I've just started a project using composer but it doesn't like unbound version constants. Would you be able to start releases of PHPAuth even if it isn't marked as a release version yet?

Thanks :+1: 

Liv

**Comment by cuonic** [comment]
I'll see what I can do !

**Comment by cuonic** [comment]
Created release v1.0.0: https://github.com/PHPAuth/PHPAuth/releases/tag/v1.0.0

Try that and tell me how it goes.

**Comment by livmackintosh** [comment]
Works a treat - thank you! :+1: I've added a pull request fixing composer support too :) 

Liv

**Comment by cuonic** [comment]
Merged, thanks for your contribution !

**Comment by livmackintosh** [comment]
Hi, sorry to be a pain again, the only last thing is to create a new release so that the composer.json is present - then autoloading should work :) x

Liv
