### ISSUE TITLE
New release needed to reflect changes to composer.json

### ISSUE THREAD

**Issue by livmackintosh** [PHPAuth/PHPAuth#134]
Sorry to be a pain again, for autoloading to work, the new composer.json has to be in each release.

Liv

**Comment by cuonic** [comment]
No problem, added v1.0.1: https://github.com/PHPAuth/PHPAuth/releases/tag/v1.0.1

Does that work for you ?

**Comment by livmackintosh** [comment]
Works but forgot to change dependency from "PHPAuth" to "phpauth/phpauth". It has to match the name in composer.json :smile_cat:

**Comment by cuonic** [comment]
Like this: 786e9127c4a1290e8cdbba44bda6d732608a89c0 ?
