### ISSUE TITLE
Dynamic database field names

### ISSUE THREAD

**Issue by Proliner** [PHPAuth/PHPAuth#138]
Field names for the table users should also be dynamic just like the table names. In addition what is the best way to make PHPAuth work with different field names. For example I change id to user_id, email to user_email etc. I really want to keep consistency in my database.

Thanks.

**Comment by cuonic** [comment]
That would add a whole new level of complexity

**Comment by livmackintosh** [comment]
I think it would be kind of 'cool' to have this option but is there really a significant use case for having different field names? I think changing the field names would make any error reporting and debugging so much harder?

**Comment by cuonic** [comment]
I do think we need to improve the field names (`uid` to `userId` for example) and respect a certain convention throughout the database table (I started working on this in the `groups` branch), but adding dynamic field labels would add a new level of complexity that most users will not be able to understand, will not be exceptionally useful, and debugging problems with certain fields could become a living hell as @livmackintosh stated, so I'm against making field names dynamic.

**Comment by mooztik** [comment]
same for me. this is going to be too complicated.
but for clear naming, PHPAuth can add a prefix to it's tables

**Comment by Proliner** [comment]
A prefix would be a nice solution can you please implement this?

Op wo 14 okt. 2015 10:27 schreef mooztik <notifications@github.com>:

**Comment by KarelWintersky** [comment]
Prefix **not** required.

Database schemes in `database_defs` folder are **example schemes**. 

You must tune up it before creating tables in your database. 

So, I renamed some tables to `phpauth_*` and added some new

**Comment by KarelWintersky** [comment]
fixed with https://github.com/PHPAuth/PHPAuth/commit/36aa45fc0ae3d5b3a38dbfb9575bd02662fcb86f
