### ISSUE TITLE
[Suggestion] move PHPMailer to a composer dependency

### ISSUE THREAD

**Issue by ryanlauterbach** [PHPAuth/PHPAuth#143]
You may have a reason for not doing this, just might clean up the source a bit.  In the future you could also have the ability to inject a mail object so developers can use swiftmailer or phpmailer or something else.

Great library, thanks.

**Comment by cuonic** [comment]
That is definitely how things should be, I'm just not sure about how to implement such a solution.

**Comment by mooztik** [comment]
plugin !  :)

**Comment by ryanlauterbach** [comment]
Yes, and how will the plugins work?  My first comment was hinting at dependency injection using pimple or similar.  You could roll your own interface/abstract class and the plugin could be a singleton extending that.

symfony, wordpress, etc. all have plugins/extensions so you could look at how they do it, although it would probably be overkill for this app.

I would also vote to move the config stuff out of the database and into a json config file, would make it easier for you and others to override, plus upgrading is a hassle with the database.  I don't use the email column for instance, I use a username column.  I've had to change lots of code, but if the column names were in the config it would be much more flexible.  And a json file would make that easy.

Lots of ideas!!

**Comment by cuonic** [comment]
Done with commit 8014721c02a81ae0ff54d36242b2c1c39936ba35
