### ISSUE TITLE
Use Zxcvbn to validate passwords

### ISSUE THREAD

**Issue by cuonic** [PHPAuth/PHPAuth#148]
Reading [this](http://ryanwinchester.ca/post/stop-forcing-your-arbitrary-password-rules-on-me) blog post made me think about password requirements: a password like `correct horse battery staple` is *very* secure (according to howsecureismypassword.net it would take 154 octillion years to crack it on a desktop PC. The problem is that with the current password requirements included with PHPAuth a password like `correct horse battery staple` would not meet the requirements, although it is secure, whereas something like `1337P@$$` would meet the requirements but is a lot less secure (requires only 3 hours to crack on a desktop PC).

A solution to such a problem would be to check the password's entropy, instead of the fact that it contains 1 uppercase letter, 1 digit... A solution already exists: https://github.com/bjeavons/zxcvbn-php and can be easily integrated into the project, giving a score to each password, and the system would check whether the password reaches a minimum score (configurable).

What do you think ?

**Comment by bugada** [comment]
Yes imho is a good idea, a minimum score can be customized in the config table.

**Comment by cuonic** [comment]
Now using zxcvb and passing tests as of commit 0db7815
