### ISSUE TITLE
getSessionHash() : Notice:  Undefined index: authID in....

### ISSUE THREAD

**Issue by human-inhabitant** [PHPAuth/PHPAuth#149]
Not super critical, but if by chance there isn't a cookie in place, an error is thrown.
```php
// I used it this way, to maintain your return type.
if ( isset( $_COOKIE[$this->config->cookie_name] ) ) {
    return $_COOKIE[$this->config->cookie_name];
}
return '';
```

**Comment by lambasoft** [comment]
I came here to post that.
This is happening because the Cookie isn't set anywhere in the code.

I'll try to fix this and hit you with a reply

**Comment by lambasoft** [comment]
In the Auth.php file, on line 114
Replace to this:

		$sessiondata = $this->addSession($user['uid'], $remember);
		if($sessiondata == false) {
			$return['message'] = $this->lang["system_error"] . " #01";
			return $return;
		}else{
			//Set the cookie
			setcookie($this->config->cookie_name,$sessiondata['hash'],$sessiondata['expiretime']);
		}

**Comment by human-inhabitant** [comment]
I didn't realize it was setting the cookie there, my bad, I was working off the login info from the [wiki](https://github.com/PHPAuth/PHPAuth/wiki/Class-Methods#login). I guess was under the impression the session cookie ~~would~~ should be set after a successful login.

> login
>
> Description:
> Authenticates a user with the system. **Note:** *You need to take the returned session hash and create the session cookie, the method does not do this for you.*

Cool, so I'll close this,...
