### ISSUE TITLE
Config constructor incorrectly sets the config table name from method param

### ISSUE THREAD

**Issue by michaleczky** [PHPAuth/PHPAuth#158]
The constructor incorrectly sets the config table's name in Config.php line 25. This cause you cannot create prefixed tables in the db.
Suggested change:
            $this->config_table = $config_table;

**Comment by hstewart** [comment]
the prepare statement inside the __set function further down will also need to be updated to reflect the changed parameter name: 

eg:
$query = $this->dbh->prepare("UPDATE {$this->config_table} SET value = ? WHERE setting = ?");

**Comment by human-inhabitant** [comment]
https://github.com/PHPAuth/PHPAuth/issues/147
