### ISSUE TITLE
different DB tables names

### ISSUE THREAD

**Issue by DiegoWtf** [PHPAuth/PHPAuth#162]
Is it real to make a prefix for DB tables names? For example, "config" -> "phpauth_config" and etc.

**Comment by i4j5** [comment]
$config = new PHPAuth\Config($dbh, 'phpauth_config');

**Comment by DiegoWtf** [comment]
And other tables?

**Comment by i4j5** [comment]
Other tables found in "phpauth_config"

database_mysql.sql
...
('table_attempts', 'attempts'),
('table_requests', 'requests'),
('table_sessions', 'sessions'),
('table_users', 'users'),
...

**Comment by DiegoWtf** [comment]
Thanks. Now I understand but it's not obvious from readme...
