### ISSUE TITLE
Getting Started

### ISSUE THREAD

**Issue by clarkewing** [PHPAuth/PHPAuth#164]
It would be nice to have a few "Getting Started" files to help users with less knowhow integrate PHPAuth into their projects (it would definitely help me!).
I could picture login.php, register.php, forgot.php, etc...

**Comment by humfricz** [comment]
@clarkewing that would be of good help to newbies

**Comment by JacquesLoubser** [comment]
I was hacking away at something like this, but the last couple of months my work has consumed all of my time :(

**Comment by cuonic** [comment]
@JacquesLoubser Do you still have these files, if you would share them with me I could also participate.

**Comment by studioaustral** [comment]
@JacquesLoubser yes, these files would be very helpful to newbies like me....

**Comment by JacquesLoubser** [comment]
Sorry @cuonic I missed the message somehow. Yes I do still have it. It is very basic, so don't expect much. Will look for them and post ASAP

**Comment by beschizza** [comment]
Yes! I'm a bit baffled too! A very basic demo application would be much appreciated, even if it's just a login-check include and some examples of each function.

**Comment by JacquesLoubser** [comment]
Those files have seemed to have gone to the island of lost socks :( I am going to start up a new project in the near future, an will pass along some beginner files. Sorry for the delay.
