### ISSUE TITLE
Anyone interested in rewriting PHPAuth correctly with me ?

### ISSUE THREAD

**Issue by cuonic** [PHPAuth/PHPAuth#165]
I was wondering if anyone would like to help me out rewriting PHPAuth in full OOP, correctly, respecting [SOLID](https://en.wikipedia.org/wiki/SOLID_%28object-oriented_design%29) standards, allowing easy modifications with plugins.

If you are at all interested please say so.

**Comment by humfricz** [comment]
i am in

**Comment by Conver** [comment]
@cuonic, do we have a plan over the new version or?

**Comment by cuonic** [comment]
@humfricz Great ! I'll setup a projet

@Conver I don't understand, there is no plan for the minute but that can be quickly established.

**Comment by Conver** [comment]
@cuonic, I just mean what do you want rewritting, beside into SOLID. New functions? new behaves?

**Comment by cuonic** [comment]
Using single responsibility classes: a class for a User, another for the Session. Each class can perform specific actions, and everything is more easily extendible making way for plugins.

**Comment by mooztik** [comment]
why not. 
i have purely abandoned the plugin system due to so many limitations...and some missing answers from you about what i've done on it.
 then, building something more easy to manipulate is not a bad idea.
i m just wondering what way(s) can be used to achieve that ...
going to a framework is one of the solutions, but i don't like the idea, because i m using my own code, and don't want to dig into learning many things to just use the PHPAuth part.
i don't want a 'machine a gaz'

and not breaking the way PHPAuth is working actually will help actual users to  move easily to the new one. but can me impossible depending the way it will be rebuilt.

so many questions :D

**Comment by cuonic** [comment]
Indeed, the fact that the current PHPAuth is not actual OOP will definitely limit plugin possibilities. Sorry I haven't answered all of your questions, I will try to be more active in the future.

I'm not looking for a *machine à gaz* or a framework, I was thinking of having the same functionality as the current PHPAuth, but respecting OOP principles. 

I'm afraid this move will probably break current implementations but an "adapter" could be made available for users that don't want to have to change all their current code.

**Comment by cuonic** [comment]
I have started thinking about how this could be implemented, here's what I've got so far:

![class-diagram-21-12-15](https://cloud.githubusercontent.com/assets/821228/11931926/cb4e2d4c-a7f1-11e5-8183-cfd81a2bea4e.png)

**Comment by kheera** [comment]
I'd also like to join this effort.

**Comment by cuonic** [comment]
@kheera Great, welcome aboard !

I've added you all to [the following repo](https://github.com/PHPAuth/ABetterPHPAuth) with write access. I've added a README and my current class diagram to the wiki, but need your help to improve and add to it before creating the classes.

**Comment by kheera** [comment]
Great, thanks. Is there someplace where we can discuss goals/design/progress/tasks? A slack group perhaps or something else? I could setup something if needed.

**Comment by cuonic** [comment]
I've setup a Mattermost team: http://mattermost.tekno.pw/abetterphpauth

**Comment by iNewLegend** [comment]
i think you run bro ...the group... and you want to build something new i think its bad idea you already have good rep in `PHPAuth` why not update and fix it and clear it as much as possible then u can make new PHPAuth version (release) with group system

**Comment by cuonic** [comment]
@iNewLegend I'm not trying to build something new, I would like to rebuild PHPAuth to make it into a more flexible and extensible user authentication system.

The current PHPAuth is being fixed whenever someone reports something wrong, it's just that PHPAuth is not my day job, so I can only fix issues when I have the time.

**Comment by kheera** [comment]
Anything happening with this? I have some free time for a few weeks.

**Comment by cuonic** [comment]
@kheera I've started rebuilding PHPAuth here: https://github.com/cuonic/PHPAuth 
If you're interested I can add you as a collaborator
