### ISSUE TITLE
User sessions always last one month

### ISSUE THREAD

**Issue by adamcbuckley** [PHPAuth/PHPAuth#166]
The `addSession` function of `auth.class.php` is as follows:

```php
if($remember == true) {
	$data['expire'] = date("Y-m-d H:i:s", strtotime($this->config->cookie_remember));
	$data['expiretime'] = strtotime($data['expire']);
} else {
	$data['expire'] = date("Y-m-d H:i:s", strtotime($this->config->cookie_remember));
	$data['expiretime'] = 0;
}
```

I think this code is wrong.  `cookie_remember` is set to `+1 month` by default.  The code above would cause a user session to to last for 1 month regardless of whether 'remember me' is checked or not.  I think the code should be as follows:

```php
if($remember == true) {
	$data['expire'] = date("Y-m-d H:i:s", strtotime($this->config->cookie_remember));
	$data['expiretime'] = strtotime($data['expire']);
} else {
	$data['expire'] = date("Y-m-d H:i:s", strtotime($this->config->cookie_forget));
	$data['expiretime'] = 0;
}
```

Note that in the else block we're setting the expire date to now + `cookie_forget` (which defaults to `+30 minutes`).

**Comment by cuonic** [comment]
You're absolutely right, I'll add this shortly, thanks !
