### ISSUE TITLE
Server error  500

### ISSUE THREAD

**Issue by alieslamifard** [PHPAuth/PHPAuth#167]
Hi everybody,
i build a simple index, login, logout and register page to test some features.
that's ok on local, no error occurred during register, login, logout , ... but i get server error 500 on a host.
i check this on anther host provider and another domain but still error occurred.
did i missed something or ..?

**Comment by iNewLegend** [comment]
i think you're page generate errors but you can't see them as it send error 500 (as protection i think `production mode`) u have check the error logs (try first of php errors)

**Comment by alieslamifard** [comment]
thanx @iNewLegend 
i just left one space after dbname=
