### ISSUE TITLE
I don't know what I'm doing wrong.

### ISSUE THREAD

**Issue by winged-wyvern** [PHPAuth/PHPAuth#170]
Hello guys,
So here's my problem, I can't figure out how to use isLoged method. After i use loggin and then set the cookie I keep getting "forbidden". Can any one please tell me what am I doing wrong?

<?php

include("Config.php");
include("Auth.php");

$dbh = new PDO("mysql:host=localhost;dbname=testing", "root", "");

$config = new PHPAuth\Config($dbh);
$auth   = new PHPAuth\Auth($dbh, $config);

$hash = $auth->login($_POST['username'], $_POST['pwd'],1);
//echo $hash['message'];
setcookie('authID', $hash['hash'], $hash['expire'], null, null, false, true);

if (!$auth->isLogged()) {
    header('HTTP/1.0 403 Forbidden');
    echo "Forbidden";

}
else{
    echo "connected";
    }

?>

**Comment by kheera** [comment]
First two lines... why Configphp and Authphp instead of Config.php and
Auth.php? Could that be the problem?

**Comment by winged-wyvern** [comment]
It's include("Config.php") and include("Auth.php");

**Comment by Conver** [comment]
Are you still having this problem?

**Comment by SherazAhmed93** [comment]
I have the same Problem, did you solved it by any chance? I looked up the `isLogged()` it's        ` return (isset($_COOKIE[$this->config->cookie_name]) && $this->checkSession($_COOKIE[$this->config->cookie_name]));`
I've looked up everywhere but can't find where are we setting the cookie?

**Comment by de3v0** [comment]
I'm not having this issue. I'll Post here part of my code, maybe it will help you:

`$dbh = new PDO("mysql:host=localhost;dbname=bdname", "root", "");

$config = new PHPAuth\Config($dbh);

$login = $auth->login($_POST['email'],$_POST['password'],false);

setcookie($config->cookie_name, $login['hash'], $login['expire'], $config->cookie_path, $config->cookie_domain, $config->cookie_secure, $config->cookie_http);
    header('location:home.php');`

**Comment by SherazAhmed93** [comment]
Oh great, thanks alot. I tried setting the cookie and  got similar results. Also did you unset the cookie on logout or does it just expires?

**Comment by de3v0** [comment]
No, i just use the logout funtion.
Have you logged in with success ?

After logout, do you still got the cookie ?

**Comment by SherazAhmed93** [comment]
Yes I tried this, It works on login, 
The Cookie remains, however the session stored in db is deleted. so if you logout and check isLogged(), it'll return false. 
I did unset the cookie on logout just to make it more efficient.

**Comment by kungknut** [comment]
The function `isLogged()` do return a boolean true or false nowadays. I think this issue can be closed.

**Comment by isheraz** [comment]
@winged-wyvern read through the comments

**Comment by KarelWintersky** [comment]
this issue may be **CLOSED**
