### ISSUE TITLE
Register without auto activate?

### ISSUE THREAD

**Issue by amatig** [PHPAuth/PHPAuth#171]
Hi,
can i create an account without auto activate? i have sendmail but register function auto active account.

**Comment by glowdemon1** [comment]
`	public function register($email, $password, $repeatpassword, $params = Array(), $captcha = NULL, $sendmail = NULL)`

Have you tried setting the $sendmail var to true?

**Comment by Conver** [comment]
You need to set $sendmail to false, not true. Then it will be activated on register.
