### ISSUE TITLE
sendmail spam

### ISSUE THREAD

**Issue by amatig** [PHPAuth/PHPAuth#172]
Hi,
if i use sendmail by command i don't have problem.
But on reset email i receive email on google like spam, why?

**Comment by Conver** [comment]
You need to verify your domain and add records to your DNS which allows mail servers to verify where the mails are sent from. This has nothing to do with PHPAuth. 

See this: https://support.google.com/a/answer/33786?hl=en & http://www.dkim.org/

**Comment by Jipem** [comment]
PHPMailer manages the signature of the mails via DKIM.
See this example : https://github.com/PHPMailer/PHPMailer/blob/master/examples/DKIM_sign.phps
It would be (very) good to add the possibility to configure PHPAuth with that (in Auth.php, between "$ mail-> isHTML (true);" and "if ($ type ==" activation ")")!
