### ISSUE TITLE
Idea : part user functions from auth

### ISSUE THREAD

**Issue by iNewLegend** [PHPAuth/PHPAuth#173]
Hey why not make a base for user ? 
i mean you have Config (fine) and Auth (with user functions)
why not part all user functions from auth to User.php and make Auth use them
example https://gist.github.com/iNewLegend/8ada450616ab1491e474

im not expert i just looks logical to me 
please if its not right explain me why 
thanks.

**Comment by Conver** [comment]
Whats the difference?

**Comment by cuonic** [comment]
I started this off without much knowledge of OOP and didn't seperate Users, Sessions, Requests... into different Models.

I have since started a more OOP PHPAuth version: http://github.com/cuonic/PHPAuth

**Comment by KarelWintersky** [comment]
Close issue, due outdated version
