### ISSUE TITLE
Mobile Google chrome trafic control problem

### ISSUE THREAD

**Issue by noldors** [PHPAuth/PHPAuth#175]
If you are using google chrome on iphone with control traffic option (proxy) you can not autorize normaly. After each page load has to authenticate again. In session table in field ip we have our ip and google proxy ip like this
213.34.56.4, 46.5.34.3
Maybe problem can be in this.

**Comment by Conver** [comment]
I'll fix this.

**Comment by liamjack** [comment]
It could be linked with the way we recover the user's IP, normally the proxy should pass through the original user's IP, which is what we should store in the `session` table.

According to Google's documentation (https://developer.chrome.com/multidevice/data-compression) down in the FAQ section:

![capture d ecran de 2018-01-06 19-03-27](https://user-images.githubusercontent.com/821228/34642515-804eddda-f314-11e7-80dc-f525e52630d5.png)

They use `X-Forwarded-For` to indicate the original user's IP, which is used by default if available by the `getIp` method: https://github.com/PHPAuth/PHPAuth/blob/master/Auth.php#L1386, although I'm not sure that this has been thoroughly tested, try creating a simple PHP page that calls the `getIp` method and `var_dump`'s the output to see if it is working correctly.
