### ISSUE TITLE
why the register method is always sending system error #03 when trying to register user, actually the addUser method?

### ISSUE THREAD

**Issue by tm57** [PHPAuth/PHPAuth#176]

**Comment by teuti** [comment]
Hi tm57,

I guess, it's because of the empty VALUES () on line 517 of auth.php.

**Comment by jjtainio** [comment]
The addUser -function is broken, it does not insert anything to the users -table, see line 517 on Auth.php. 

Hopefully someone fixes this.

**Comment by Conver** [comment]
Not enough information provided.
