### ISSUE TITLE
Class 'PHPAuth\PHPMailer' not found

### ISSUE THREAD

**Issue by alieslamifard** [PHPAuth/PHPAuth#179]
hi.
based on phpauth files, i used line below:
`use PHPMailer\PHPMailer\PHPMailer;`
but i see an error say : 'class not found' and i guess it's because there is no namespace in PHPMailer file.
Also in PHPMailer documentation they recommend that we must just use `require 'PHPMailerAutoload.php';` but problem still exist.
how can i fix this?
thanks.

**Comment by alieslamifard** [comment]
now i just use `$mail = new \PHPMailer;` in auth.php
and seems it's ok.
it's ok or not?

**Comment by aktiwers** [comment]
@alieslamifard Hey thanks! I had the same problem, and this fixed it. I will make a pull request.

**Comment by Conver** [comment]
See #204
