### ISSUE TITLE
Problem for change the name of config table

### ISSUE THREAD

**Issue by jesussantos** [PHPAuth/PHPAuth#184]
Hi.
The problem is the name of the config table. If I want change it i can not because the construct use the var: **$this->phpauth_config_table** and It must be **$this->config_table.**

Thanks!

**Comment by Conver** [comment]
Not sure I understand your issue? It is called "$this->config_table" and not "$this->phpauth_config_table"

**Comment by joseareland** [comment]
Hi,
The same issue here: If I need to change the name for the config table in my DB, it will fail because in the class Config there is an error calling for an undefined property: **$this->phpauth_config_table**, it should be **$this->config_table** in two spots.

**Comment by joseareland** [comment]
Hi,

I found the issue, it is related to the version downloaded using composer, it is set to "phpauth/phpauth": "^1.1", I fixed on my side using **"phpauth/phpauth": "dev-master"**.

I hope it helps for somebody else.

**Comment by KarelWintersky** [comment]
damned composer <_<

**Comment by Conver** [comment]
I'm not the biggest fan of Composer, a manual install should be possible too.

**Comment by KarelWintersky** [comment]
I HATE Composer.

**Comment by cuonic** [comment]
Composer is really useful, I started using it for this project and since it has made life much easier. You just need to read the basic instructions, and understand that when you do `composer install blah` then you will get the latest *release* of a repo, and not the current master branch.
