### ISSUE TITLE
Would you like to please help us setup PHPAuth at www.SolidarityFarm.tk ?

### ISSUE THREAD

**Issue by alexbible** [PHPAuth/PHPAuth#188]
We are a small group taking care of the fatherless in a poor area in South America.
If any of you would like to help us setup PHPAuth for our website we will be very thankful :)
Thank you!
Alex, Javier, Carina, Alejandro and Fernando

**Comment by Conver** [comment]
Hello,

If you pass me your mail, then I'll be able to help you.

**Comment by alexbible** [comment]
Hi Cover, my email is smuglovsky@gmail.com
