### ISSUE TITLE
Can't use the library

### ISSUE THREAD

**Issue by ltpitt** [PHPAuth/PHPAuth#19]
Hello there and thanks for this code!

I'm trying to implement it with a very simple test.

My page looks like this:

```php
<?php

include("config.class.php");
include("auth.class.php");

$dbh = new PDO("mysql:host=localhost;dbname=mydb", "myuser", "mypass");

$config = new Config($dbh);
$auth = new Auth($dbh, $config);

$auth->register('myemail@test.com','username','password','password');

if(isset($_COOKIE[$config->cookiename]) || !$auth->checkSession($_COOKIE[$config->cookiename])) {
    header('HTTP/1.0 403 Forbidden');
    echo "Forbidden";
    exit();
}

?>
```

If I open it using my browser I get "okokokForbidden"

What is wrong?

I'd be glad to contribute adding to the readme some noob-proof help but I need it first :)

Thanks for your time!

**Comment by Conver** [comment]
You say you get:  "okokokForbidden"
I dont see where the ok should come from?, the forbidden I do.

You are register an account, that is correct, but you still need to login afterwards.

**Comment by Conver** [comment]
Did you fix this?

**Comment by zawaruddin** [comment]
try to check the password, i think it's the problem. Password must contain at least one uppercase and lowercase character, and at least one digit.

**Comment by cuonic** [comment]
If you displayed the output of the call to the register function you will see that there is an explicit error message stating what is wrong, it's probably the fact that the password has minimum requirements as @zawaruddin said.
