### ISSUE TITLE
File to do all operation

### ISSUE THREAD

**Issue by pippuccio76** [PHPAuth/PHPAuth#191]
Hi , sorry for english . I download the zip . The answer is , this is only a class ? Ther'isnt the page to login , registrate ,logout etc ?

**Comment by Conver** [comment]
Correct, there ain't any examples yet, beside the simple one in readme.md

**Comment by KarelWintersky** [comment]
@pippuccio76 , You can find some examples of using PHPAuth here:

https://github.com/KarelWintersky/kwLiveMap
