### ISSUE TITLE
Why this class don't make Cookie and Session?

### ISSUE THREAD

**Issue by Ischiawebsoftware** [PHPAuth/PHPAuth#194]
PHPAUTH don't use COOKIE and SESSION. The session are registered only in the database?

**Comment by Conver** [comment]
We haven't added Cookies to PHPAuth as we all have different ways of manage that, so instead it returns the hash needed to be saved in a cookie or a session to be logged in.

**Comment by khucgo** [comment]
I can see that there is no setcookie() function call at all. How can you get the $_COOKIE value to use in isLogged() function?
![screenshot_1](https://cloud.githubusercontent.com/assets/5334770/16790480/a414ce26-48e0-11e6-9651-8641b5e82b72.png)
