### ISSUE TITLE
Czech localization

### ISSUE THREAD

**Issue by Marian-Kechlibar** [PHPAuth/PHPAuth#196]
Hello all,

I needed a Czech localization for the php auth package, so here it is for everybody. 

Marian

[cs_CZ.zip](https://github.com/PHPAuth/PHPAuth/files/361305/cs_CZ.zip)

**Comment by Conver** [comment]
Can you make a PR?

**Comment by Marian-Kechlibar** [comment]
What do you mean by PR?

**Comment by Marian-Kechlibar** [comment]
So here it is.

**Comment by Conver** [comment]
merged
