### ISSUE TITLE
Erroneous display of non-ASCII characters in activation/reset e-mails

### ISSUE THREAD

**Issue by Marian-Kechlibar** [PHPAuth/PHPAuth#198]
I just started working with the Czech localization that I provided today. 

Localization of error/success messages works perfectly, all non-ASCII characters are displayed correctly.

What fails horribly are the e-mails. In From:, Subject:, plaintext body and html body, the charset is explicitely given as iso-8859-1, even though it should be UTF-8. This concerns not just the text of the e-mails, but the database entries from config table as well (for example, site_name, which I set up to use some Czech characters).

I am attaching a screenshot of my deformed activation e-mail, with all the problematic declarations of charset highlighted in red. (I have erased some private info). 

This is probably just a matter of adding the charset parameter to the PHPMailer when sending the e-mail, but I am not sure how to do it, otherwise I would fix it.
![error_phpauth](https://cloud.githubusercontent.com/assets/20437910/16812641/44da86be-492e-11e6-8bf2-5ded4871f177.png)

**Comment by Conver** [comment]
Around line 48 to 61 inclass.phpmailer.php, you can change charset and encording.

You can do $mail->CharSet = "";

See more https://github.com/PHPMailer/PHPMailer/blob/master/class.phpmailer.php#L48

**Comment by Marian-Kechlibar** [comment]
OK, I created a pull request, because I believe that will influence all the users of non-ASCII national alphabets.
