### ISSUE TITLE
Setting Cookie

### ISSUE THREAD

**Issue by osbash** [PHPAuth/PHPAuth#200]
So where exactly is the cookie with the user hash being set?  I see "addSession" function, but that returns the database session data, doesn't actually set the cookie?

Then "isLogged" checks for a set cookie to determine if logged in.  I added a line to set the cookie, but wanted to make sure I'm not missing something.

**Comment by Conver** [comment]
You are correct, you have to set the cookie by yourself.

**Comment by osbash** [comment]
Okay thanks!  Now the cookie path in the config makes sense

**Comment by Conver** [comment]
Super :-)

The reason we are doing it this way is because people use different methods to set and use cookies, some set cookies using js/jquery, others just the native PHP setCookie function, so it returns the hash and information that needs to be saved in the cookie.
