### ISSUE TITLE
Languages en.php

### ISSUE THREAD

**Issue by ikennah** [PHPAuth/PHPAuth#21]
How's is the language en.php file been used. I don't see any where that this file is been referenced? And it's definitely not returning the correct messages. Am I missing something?

**Comment by Conver** [comment]
The language file is used by the auth class, to return error messages.

It is not used inside the class, but rather outside, when the auth class returns some date all is good, but when something goes wrong it returns a error string, which can be pulled from the language file to get the proper message.
