### ISSUE TITLE
What is the purpose of getRequest?

### ISSUE THREAD

**Issue by dannychase2004** [PHPAuth/PHPAuth#212]
What is the purpose of getRequest? The documentation says that it gets request data, but my question is, why would I need this?

**Comment by cuonic** [comment]
When someone requests a password reset or an activation email it's called a "request". There are two types of request: "activation" or "reset" and they are both stored in the same table called "requests".

So when you try to activate an account or reset a password via a link sent via email, the the `getRequest` method is called with the request key (a random hash) and the key type depending on what the user is trying to, either "activate" or "reset".

**Comment by dannychase2004** [comment]
Thanks!!
