### ISSUE TITLE
pg sql no primary key on config database

### ISSUE THREAD

**Issue by ddan39** [PHPAuth/PHPAuth#214]
It probably works fine in the library, but I can't edit the config table with pgadmin. It displays this warning:

> Since the table public.config doesn't have a primary key or OIDs, you can view the data only. Inserting new rows and changing existing rows isn't possible for the Edit Data tool without primary key. 
> In order to edit data, pgAdmin III requires a primary key on the table, which is a good database design practice anyway. Alternatively, the table can be created WITH OIDS. Please note that oids are not guaranteed to be unique over a very long period of time, so using oids as kind-of primary key is only second choice.

**Comment by cuonic** [comment]
Well, PGAdmin is telling us that our database is poorly designed, which is probably true, but hey !

What I've done is added an `id` column that is a primary key in the `config` table that should allow you to make modifications.
