### ISSUE TITLE
mysql errors

### ISSUE THREAD

**Issue by dimitrivisser** [PHPAuth/PHPAuth#218]
running database_informix.sql gives this error:

SQL query:

CREATE TABLE attempts (
  id SERIAL,
  ip varchar(39) NOT NULL,
  expiredate DATETIME YEAR TO SECOND,
  PRIMARY KEY (id)
);
MySQL said: Documentation

#1064 - You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'YEAR TO SECOND,
  PRIMARY KEY (id)
)' at line 4 

All attemps to "DROP TABLE" for tables that do not exist also gives errors...

running database_pgsql.sql gives this error:

SQL query:

CREATE TABLE attempts (
  id serial NOT NULL,
  ip character varying(39) NOT NULL,
  expiredate timestamp without time zone NOT NULL,
  PRIMARY KEY (id)
);
MySQL said: Documentation

#1064 - You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'without time zone NOT NULL,
  PRIMARY KEY (id)
)' at line 4 

I was so happy to have found something that "Integrates easily into most existing websites" ;-)

**Comment by InformatiqueHoules** [comment]
The "database_informix.sql" fiel is for creating the database for informix only.

Use "database_mysql.sql" instead.
