### ISSUE TITLE
Line 189

### ISSUE THREAD

**Issue by ochov1** [PHPAuth/PHPAuth#219]
This is how I use 
include('PHPAuth/Auth.php');
include('PHPAuth/Config.php');
include('PHPAuth/languages/es_MX.php');
$dbh = new PDO("mysql:host=localhost;dbname=login", "root", "");

$config = new Config($dbh);

Fatal error: Class 'Config' not found in D:\xampp\htdocs\aplic\example.php on line 9

what I do bad?

**Comment by cuonic** [comment]
Try `$config = new \PHPAuth\Config($dbh);`

Le dimanche 04 septembre 2016 à 02:30 -0700, ochov1 a écrit :
> This is how I use 
> 
> include('PHPAuth/Auth.php');
> 
> include('PHPAuth/Config.php');
> 
> include('PHPAuth/languages/es_MX.php');
> 
> $dbh = new PDO("mysql:host=localhost;dbname=login", "root", "");
> 
> $config = new Config($dbh);
> 
> > Fatal error: Class 'Config' not found in
D:\xampp\htdocs\aplic\example.php on line 9
> 
> what I do bad?
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub, or mute the thread.
> 
> 
>   
>   
> 
> 
> 
> 
> 
> 
> > > > > > > > > > > > {"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c5
5493e4bb","name":"GitHub"},"entity":{"external_key":"github/PHPAuth/P
HPAuth","title":"PHPAuth/PHPAuth","subtitle":"GitHub
repository","main_image_url":"https://cloud.githubusercontent.com/ass
ets/143418/17495839/a5054eac-5d88-11e6-95fc-
7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent
.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-
b52498112777.png","action":{"name":"Open in
GitHub","url":"https://github.com/PHPAuth/PHPAuth"}},"updates":{"snip
pets":[{"icon":"DESCRIPTION","message":"Line 189
(#219)"}],"action":{"name":"View
Issue","url":"https://github.com/PHPAuth/PHPAuth/issues/219"}}}

**Comment by ochov1** [comment]
ok!!! Thank you
