### ISSUE TITLE
parse error in original code?

### ISSUE THREAD

**Issue by dpf-dd** [PHPAuth/PHPAuth#22]
I really would like to use your class, but unfortunately I didn't get it running.

$auth = new Auth($dbh, $config); => this is producing the following parse error:
"Parse error: syntax error, unexpected '[' in auth.class.php on line 198"

I tried it with original files on two different webservers, both didn't work and throw this error...
I also checked the requirements and my used software (php, mysql) is up-to-date and can't be the problem...

What am I doing wrong? I'm pretty sure I do so, because noone else in the whole internet seems to get this error on usage -.-

Thanks in advance for your help :)
Best regards, dpf-dd

**Comment by Conver** [comment]
Hello there, 

I'm not sure what causing your problem, been checking files and such, but can't find it.

What system are you trying on? OS, webserver, PHP etc?

**Comment by zawaruddin** [comment]
yeah me too... last night i've same problem. So i tried to upgrade my php (from php 5.3 to 5.4) and it's work..

**Comment by dpf-dd** [comment]
I'm running PHP Version 5.3.10-1ubuntu3.15 - so it should work referring to the requirements (5.3.7)...
Unfortunately I'm not able to update the PHP Version to 5.4
Nevertheless I found another good documented solution that worked for me, so I don't need this time waster anymore :)
