### ISSUE TITLE
phpAuth with api

### ISSUE THREAD

**Issue by alieslamifard** [PHPAuth/PHPAuth#223]
hi
i use PHPAuth and it's excellent.
but now i need it in a project with api.
actually i use slimframework and i need this for user authenticating.
please create a new project of PHPAuth that works with api

**Comment by Conver** [comment]
It always works with API?

It's a class and you can do with it like you wish, no limits.

Else, you need to explain better what you need.

**Comment by alieslamifard** [comment]
Thanks for ur fast reply.
I have a question, i know that it work with ip and a unique token, so if i want to use it as an api for login and register in android device i have not any ip (maybe, i dont know!), so what is the solution?

**Comment by Conver** [comment]
You still have the IP of the device. else you have the UUID, there are many solutions, Google is your friend.

**Comment by cuonic** [comment]
Oh sure no problem we'll just create a new project just for you

Le mardi 20 septembre 2016 à 11:39 -0700, Ali eslamifard a écrit :
> hi
> 
> i use PHPAuth and it's excellent.
> 
> but now i need it in a project with api.
> 
> actually i use slimframework and i need this for user authenticating.
> 
> please create a new project of PHPAuth that works with api
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub, or mute the thread.
> 
> 
>   
>   
> 
> 
> 
> 
> 
> 
> > > > > > > > > > > > {"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c5
5493e4bb","name":"GitHub"},"entity":{"external_key":"github/PHPAuth/P
HPAuth","title":"PHPAuth/PHPAuth","subtitle":"GitHub
repository","main_image_url":"https://cloud.githubusercontent.com/ass
ets/143418/17495839/a5054eac-5d88-11e6-95fc-
7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent
.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-
b52498112777.png","action":{"name":"Open in
GitHub","url":"https://github.com/PHPAuth/PHPAuth"}},"updates":{"snip
pets":[{"icon":"DESCRIPTION","message":"phpAuth with api
(#223)"}],"action":{"name":"View
Issue","url":"https://github.com/PHPAuth/PHPAuth/issues/223"}}}

**Comment by alieslamifard** [comment]
login function set a cookie on browser based on remember option.
i write an api that send username,password for login and do not need to set cookie! because i just send hash as header on another request to all api's. so how can i disable set cookie without send remember as zero?
i see addSession function but i do not understand it's logic to set cookie.

**Comment by Conver** [comment]
Don't use PHPAuth, if you dont know how to program.. 

We cannot help everyone using this class.. 

And also, PHPAuth, does not set any cookies... You do that..

CLOSED!!

**Comment by alieslamifard** [comment]
right!
i must learn program and you must learn how to behave...

**Comment by LiamJack** [comment]
"right!
i must learn program and you must learn how to behave..."

This is quality material
