### ISSUE TITLE
System error while trying to register

### ISSUE THREAD

**Issue by MahdiPOnline** [PHPAuth/PHPAuth#23]
I've got a problem with PHPauth. I can't get the framework to insert a row. Of course it's connected to the database and it can insert the query to 'requests' table but it won't add the row to 'users' table and throws a 'system_error'.
I connect to it through my own controller class. Here's the code for registration page.

```
$register = $ctr->get_phpauth()->register($_POST['email'], $_POST['username'], $_POST['password'], $_POST['repeatpassword']);
```

I can't test anything else since I can't add any user.

**Comment by Conver** [comment]
Try to debug where the 'system_error' is coming from.

Its hard for me to help you with the provided information.

Is php mail installed?

**Comment by MahdiPOnline** [comment]
'system_error' is comming from the exectue command in function addUser, line 510.
I'm using Xampp on Ubuntu and based on the info in the Internet, I only changed php.ini in order to activate php mail, which didn't solve the issue

**Comment by Conver** [comment]
Okay then. So the error comes when trying to add th e empty row into database, not sure why you can't do it, I'll need to research it, as I never seen the problem before.

And you are sure it isn't something with your own controller?
- Will reply back if I find a solution, but please debug your own controller, as I think the problem is there.

**Comment by MahdiPOnline** [comment]
I've checked everything. Controller is fine. Every other class imported works fine. It's completely functional but PHPAuth. I never had any problems with PHPAuth up until now.
The error is coming from the Execute command right after Prepare function. It happens while trying to register and it happens only once because after the first time a row is added to table 'requests' and it stops the query from launching again. This is the row added to that table, if it can help you.

```
id => 0
uid => 0
rkey => 8QJAWB5Ca44gb7nO28C0
expire => 2015-02-27 00:52:34
type => activation
```

This is as much as information I can give! And if there is anything I can do to help, I'll be more than happy to do it.

**Comment by Conver** [comment]
I think I know what the reason is now, please check your tables if the id field is auto increment

**Comment by MahdiPOnline** [comment]
Even with AI activated it gives the same error.
AI wasn't in the database sql file.

**Comment by cyking** [comment]
I had a similar problem. I traced the error to `if(!mail($email, $subject, $message, $headers))`     
   
Turns out I forgotten to install a MTA Agent for my test server.  After installing nullmailer, everything worked fine.     

;-)

**Comment by MahdiPOnline** [comment]
Thanks man. Although I switched to my own framework. Anyways, thank you very much.
