### ISSUE TITLE
adding feature for users group

### ISSUE THREAD

**Issue by zawaruddin** [PHPAuth/PHPAuth#24]
hi there ...

I think it would be good if you add some features for users group access control like admin page just for the admin group etc.

I tried to add this feature, but it's not finished yet

hopes to be added to the next list :)

**Comment by Conver** [comment]
Good idea, I'll add it to the list.

**Comment by robawolf** [comment]
Agreed.  Would love to see 'account types' built in... I thought maybe to create a separate database for a different class of user... but that's not very graceful.

Also, what would you recommend for storing additional data on a user?  Add a table and relate to the user id, I suppose... but I mean... could additional data be stored in the same cookie?

**Comment by cuonic** [comment]
Added basic group functionality in a new branch called "groups": https://github.com/PHPAuth/PHPAuth/tree/groups

Needs testing.
