### ISSUE TITLE
Composer support

### ISSUE THREAD

**Issue by PaulKish** [PHPAuth/PHPAuth#25]
I love that the script is getting a reboot, composer support would be a good feature

**Comment by Conver** [comment]
That is a good idea, we'll include that in the next release, which will be the new rewritten auth.

tho I am a PHP developer, I've never used composer, so will need to research how to use it, so we can add it to this auth.

**Comment by PaulKish** [comment]
@Conver , when you say the new rewritten auth, do you mean this current auth is getting rewritten?

**Comment by Conver** [comment]
@PaulKish, Yes, that is what I mean. the current version is being rewritten.

We'll do our best to make it backwards compatible. 

The current version lacks of many things, so a completely rewriting is necessary.
But the new version will so much better. it will include more functions, better security, better mailing etc.

Let me know if you are worried about the update, and why.

**Comment by PaulKish** [comment]
@Conver good idea indeed, I was just wondering what is the state of the current repo, can I use it in developing an application or would it be best to wait for it to mature further?

**Comment by Conver** [comment]
The current version is stable is it, but is lacking many things.

yes, you can use it, and we'll do our best to make it backwards compatible or make a convert script.
- So in short, Yes, do use it! :)

**Comment by PaulKish** [comment]
@Conver :+1:

**Comment by Conver** [comment]
@PaulKish you can see some of the information about the new release here: (#6)
Notice, That issue is only a bit of the new release, but suggestions and what else have been located there.

**Comment by c0d3z3r0** [comment]
@Conver Thank you for your great work! When will the new release be published?

**Comment by Conver** [comment]
@c0d3z3r0, your very welcome.

We ain't sure when the new release will be published, both me and @cuonic is very busy atm.

**Comment by butchewing** [comment]
Create a new branch and put the new auth on there. We can help!

**Comment by Conver** [comment]
@butchewing, that could be an idea to do. We haven't though of that, since there haven't been much help from the community. (code wide).

Let me see what I can do, maybe I can do it in one of the follow days.

**Comment by lospo** [comment]
Hi, and good morning.
Is there any example of all the feature of this class?
I see only "how to secure a page"

THANKS

**Comment by Conver** [comment]
@PaulKish, @c0d3z3r0, added to the list: https://github.com/PHPAuth/PHPAuth/wiki/Todo-list

**Comment by Conver** [comment]
I like the option to install through Composer, but I do enjoy setting up manually too.

So as long as both option gives the same result, it should be just fine.

**Comment by Conver** [comment]
@PHPAuth/developers If you know how Composer works, then fell free to PR, I do not plan on researching Composer atm.

**Comment by PaulKish** [comment]
Will take this up, let me see if I can get sometime this weekend

**Comment by cuonic** [comment]
Added Composer support with commit 783ca7ba6e4a73390effaa815d9d30268ba8424f, could you give it a go @PaulKish ?

**Comment by livmackintosh** [comment]
@PaulKish Added a pull request with Composer support so you should be good to go if it's accepted :smile: Note that you'll need to add it as a VCS repository for now as it's not yet on Packagist.

Liv

**Comment by cuonic** [comment]
Composer is now supported and functional, thanks to @livmackintosh
