### ISSUE TITLE
Autoincrement Table Primary Keys

### ISSUE THREAD

**Issue by PaulKish** [PHPAuth/PHPAuth#26]
Hi, I noted that the database schema contains table whose primary keys are not auto-incrementing, this causes issues usually on the second insert of data, for example creating the first user has no issues, subsequent additions result in the system error message being displayed. On my end I was able to fix this by simply auto-incrementing the primary key.

**Comment by cuonic** [comment]
Fixed with 6e9f0c7d8c70481301fdd6e3c56665dffd5da74c
