### ISSUE TITLE
PHP Parse error:  syntax error in auth.class.php

### ISSUE THREAD

**Issue by Tverskoy** [PHPAuth/PHPAuth#27]
Hello Everyone!

So, when I wanted to run this script, the word error:

`PHP Parse error:  syntax error, unexpected '[' in auth.class.php on line 198`

In the above line saw the following structure:

`if($this->getUser($getRequest['uid'])['isactive'] == 1) {`

php -v
PHP 5.3.10-1ubuntu3.16 with Suhosin-Patch (cli) (built: Feb 13 2015 20:15:04)

**Comment by Conver** [comment]
That should work, I'll debug it and see what I can come up with.

**Comment by djlaidler** [comment]
Same issue...

PHP Parse error: syntax error, unexpected '[' in auth.class.php on line 198

Also on ln 249, 302, 389, 666, 955

if ($this->addRequest($query->fetch(PDO::FETCH_ASSOC)['id'], $email, "reset")['error'] == 1) {
return $query->fetch(PDO::FETCH_ASSOC)['id'];
return $query->fetch(PDO::FETCH_ASSOC)['uid'];
if($type == "activation" && $this->getUser($uid)['isactive'] == 1) {
if ($this->getUser($row['id'])['isactive'] == 1) {

Using PHP 5.3.27

**Comment by djlaidler** [comment]
I resolved each issue by editting;

EG/ if($this->getUser($getRequest['uid'])['isactive'] == 1) {
TO
$user = $this->getUser($getRequest['uid']);
if($user['isactive'] == 1) {

**Comment by Conver** [comment]
Hmm, We'll debug it.. It should work otherwise.

Not sure why $var->action()['object'] only works on some, have always worked on all system I've worked on.

**Comment by cuonic** [comment]
Fixed with 6e9f0c7d8c70481301fdd6e3c56665dffd5da74c

**Comment by cuonic** [comment]
Function dereferencing was introduced in [PHP 5.4](https://php.net/manual/en/migration54.new-features.php) hence why it isn't working on systems running PHP 5.3.27. I was unaware of this and will fix the README to indicate that the class only supports PHP 5.4 and up.
