### ISSUE TITLE
How to use with PHP Sessions?

### ISSUE THREAD

**Issue by ChristianFranke** [PHPAuth/PHPAuth#279]
Is there a "best practice" to use PHPauth with PHP sessions? I need PHP sessions to store data.

For example, should I use the same cookie_name for the PHP session and PHPauth? Is there an example for doing this?

**Comment by Conver** [comment]
As of writing PHPAuth uses cookies, but should be easy enough to make use sessions instead.

**Comment by liamjack** [comment]
PHPAuth uses it's own session system, bypassing PHP's native sessions, and storing information in a database to overcome multiple limitations encountered with the native counterpart. 

For now, there is no way to link a PHPAuth session with a native PHP session.

**Comment by ChristianFranke** [comment]
Okey, I think I can work without PHP sessions, but how do I store data in PHPauth? 

For example, in the first request I store data with..
`$_SESSION['test'] = [ 'foo' => 'bar' ];`

On the next request I can use the stored value with
`var_dump($_SESSION['test']);`

How can this be done with PHPauth?

**Comment by liamjack** [comment]
This is currently not possible with PHPAuth at the moment, ideally a session system with data storage should be on the roadmap.

**Comment by liamjack** [comment]
Created issue #280 for further discussion about session storage.
