### ISSUE TITLE
Sessions - Allow storing key / value pairs along with the session

### ISSUE THREAD

**Issue by liamjack** [PHPAuth/PHPAuth#280]
With PHP's native session storage session, it is possible to store key / value pairs with `$_SESSION['key'] = "value";` for example. Something similar would be good with PHPAuth's session system.

**Comment by KarelWintersky** [comment]
Storing additional data must be implemented with wrapper class over PHPAuth. Methods of storing that data may be different: redis, mongo, file-sessions, etc. 

It is not a PHPAuth's mission.

PHPAuth core stores only data required for authentication user.

**Comment by KarelWintersky** [comment]
So, our our wiki must contain (it is my task) example of that PHPAuth-wrapper code. 

@KarelWintersky !
