### ISSUE TITLE
Cookie not set

### ISSUE THREAD

**Issue by djlimix** [PHPAuth/PHPAuth#283]
Hi,
I have problem with login. The cookie won't set after login. Why?
`$login = $auth->login( $username, $password, TRUE );`
`setcookie(
			$config->cookie_name,
			$login['hash'],
			$login['expire'],
			$config->cookie_path,
			$config->cookie_domain,
			$config->cookie_secure,
			$config->cookie_http
		);`

**Comment by kungknut** [comment]
Will please post the PHP snippet where the evaluation is made?

Also make sure `$username` and `$password` contains valid credentials as present in the database table named users, and that the user is active.
