### ISSUE TITLE
Hungarian translation

### ISSUE THREAD

**Issue by akikari** [PHPAuth/PHPAuth#284]
Hello,

I found some issues in the original _hu_HU.php_ file which I have corrected. Can someone check and upload? The _hu_HU_diff.php_ file contains both texts for verification. The _hu_HU.php_ file contains new texts only.

[PHPAuth_languages.zip](https://github.com/PHPAuth/PHPAuth/files/1669885/PHPAuth_languages.zip)

Thanks.

**Comment by KarelWintersky** [comment]
Updated in PR #294 
Close after merge
