### ISSUE TITLE
Microsoft SQL Server error

### ISSUE THREAD

**Issue by akikari** [PHPAuth/PHPAuth#285]
When using Microsoft SQL Server I get the following error:
> PDOStatement::fetchAll(): SQLSTATE[HY000]: General error: PDO::FETCH_KEY_PAIR fetch mode requires the result set to contain extactly 2 columns.

The problem is that the config table contains 3 columns (see _database_mssql.sql_ in the PHPAuth root directory) while the _Config_ class wants to convert the result to key-value pairs (_Config.php_ line 31).

**Possible solutions**

- Shouldn't use the _id_ column in the _config_ table.
- Modify SQL command in the _Config.php_ line 30:
`$query = $this->dbh->query("SELECT setting, value FROM {$this->config_table}");`

Please investigate _database_pgsql.sql_ too.

Thanks

**Comment by KarelWintersky** [comment]
Solved in #59c239999e741d47752af5290e107a46d828c838
