### ISSUE TITLE
Install without Composer

### ISSUE THREAD

**Issue by rayigen85** [PHPAuth/PHPAuth#286]
Hello, is there an option to install PHPAuth without Composer?
I have only a Webspace an can´t access the cli.

**Comment by kungknut** [comment]
Hi!

Indeed there is. The only package PHPAuth is depending on is the PHPMailer. Simply download both packages and upload them to your server.

In the head of the page you want to protect or login/register/forgot password form pages, include PHPAuth as shown in the example in the readme, and include PHPMailer alongside it. Then you should be fine.

Don't forget to set up your SQL-server as of the template files in the project root.

**Comment by rayigen85** [comment]
Good morning,
and thanks for the answer. I had try this befor, when i include the PHPAuth/config.php an Auth.php, is there an Error in Auth.php "Fatal error: Uncaught Error: Class 'ZxcvbnPhp\Zxcvbn' not found in /www/htdocs/w013c81b/raybit.de/app/PHPAuth-master/Auth.php:189 Stack trace: #94"

**Comment by kungknut** [comment]
Ah, missed that dependency, I'm sorry. Have a look at https://github.com/bjeavons/zxcvbn-php. Simply upload it to your server and include it in the beginning of your file.

**Comment by rayigen85** [comment]
I had try this too ;-)
But zxcvbn has another dependencys, and the errors become more and more ;-(

**Comment by kungknut** [comment]
When running `php composer.phar require PHPAuth/PHPAuth` from within an otherwise empty web root it is not downloading anything but the repositories mentioned above.

Maybe someone else can help out?

**Running complete install using composer (Using PHPAuth release 1.1.1):**

```
user@websrv:/var/www/public_html$ php composer.phar require PHPAuth/PHPAuth
Using version ^1.1 for phpauth/phpauth
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Package operations: 3 installs, 0 updates, 0 removals
  - Installing bjeavons/zxcvbn-php (0.3.0): Loading from cache
  - Installing phpmailer/phpmailer (v5.2.26): Loading from cache
  - Installing phpauth/phpauth (1.1.1): Downloading (100%)
phpmailer/phpmailer suggests installing league/oauth2-google (Needed for Google XOAUTH2 authentication)
Writing lock file
Generating autoload files
```

**When uploading PHPAuth-folder to web root and running composer from within it (Using PHPAuth-master):**

```
user@websrv:/var/www/public_html$ php composer.phar install
Loading composer repositories with package information
Updating dependencies (including require-dev)
Package operations: 2 installs, 0 updates, 0 removals
  - Installing bjeavons/zxcvbn-php (0.3.0): Downloading (100%)
  - Installing phpmailer/phpmailer (v5.2.26): Downloading (100%)
phpmailer/phpmailer suggests installing league/oauth2-google (Needed for Google XOAUTH2 authentication)
Writing lock file
Generating autoload files
```
