### ISSUE TITLE
Change email has no checks on new email

### ISSUE THREAD

**Issue by phrenopolis** [PHPAuth/PHPAuth#288]
When registering a new user, we check to see that the email is not currently in use. There is also an option to verify the user's ownership of that email address by sending an activation email. All good!

When changing from one email to another, neither of those checks is implemented. Which makes it trivial for someone to move their account to any email address they like, including those they do not own, and those that already exist in the database - creating who knows what sort of havoc? If privileges are tied to accounts which are tied to email addresses and those are not guaranteed to be unique...

**Comment by KarelWintersky** [comment]
Solved.
