### ISSUE TITLE
Login failure with first user

### ISSUE THREAD

**Issue by iautomation** [PHPAuth/PHPAuth#29]
Line *67* of _auth.class.php_ states:
```if(!$uid) {```
If the user id is 0(first row of database), this line blocks login.
It needs to be:
```if($uid===false) {```

Thanks for the great class.
Best

**Comment by cuonic** [comment]
@iautomation The user ID should never be 0, theoretically the first user should be UID 1. There was a problem with auto-increment in the previous versions but I fixed this recently, are you using the latest database schema and class ?

**Comment by iautomation** [comment]
Ah, it looks like the real issue is with the database schema then. In line *64* of *database.sql*:
````id` int(11) NOT NULL,```
is not autoincremented

**Comment by iautomation** [comment]
Sure, thx for your help
