### ISSUE TITLE
PHPAuthConfig - Call to a member function fetch() on boolean.

### ISSUE THREAD

**Issue by timolinn** [PHPAuth/PHPAuth#299]
I'm trying to load the configuration from an array but gets this error: 
`Fatal error: Uncaught Error: Call to a member function fetch() on boolean in C:\***\***\vendor\phpauth\phpauth\Config.php:32`

Here's my code:
      `use PHPAuth\Config as PHPAuthConfig;
        use PHPAuth\Auth as PHPAuth;

      // load connnection from IoC container
        $pdo = app('connection')->getPDO();

        $config = new PHPAuthConfig($pdo, 'array', app('config')->get('auth'));

       $phpauth = new PHPAuth($pdo, $config);

      $params = [
            'user_name' => $data['username'],
            'first_name' => $data['firstname'],
            'last_name' => $data['lastname'],
            'phone_number' => $data['phonenumber']
        ];

        $newU = $phpauth->register(
            $email, $password, $confirmedpassword, $params, null, true
        );

     return $newU;`

I looked at the source I figured PHPAuth is still trying to load configuration from the database:
`"Config.php"

 public function __construct(\PDO $dbh, $config_table = 'config')
    {
        $this->dbh = $dbh;

        if (func_num_args() > 1) {
            $this->config_table = $config_table;
        }

        $this->config = array();

        $query = $this->dbh->query("SELECT * FROM {$this->config_table}");

        while($row = $query->fetch()) {
            $this->config[$row['setting']] = $row['value'];
        }

        $this->setForgottenDefaults(); // Danger foreseen is half avoided.
    }`

Please what am I missing? Thanks in advance.

**Comment by timolinn** [comment]
I installed with  `composer require phpauth/phpauth`  Well... turns out phpauth composer package is not updated yet.

Adding
`"require": {
        "phpauth/phpauth": "dev-master",
    },`

and running `composer update` solved it. Thank you.

**Comment by KarelWintersky** [comment]
Thank you. I'll update current `README.md`
