### ISSUE TITLE
Readme - Ghit.me counter

### ISSUE THREAD

**Issue by liamjack** [PHPAuth/PHPAuth#300]
Does the Ghit.me counter in the readme work for anyone ?

![capture d ecran de 2018-04-26 15-13-12](https://user-images.githubusercontent.com/821228/39307937-7879ab66-4964-11e8-88d4-e46564960f53.png)

**Comment by KarelWintersky** [comment]
No, because ghit.me service is **down**.

See https://downforeveryoneorjustme.com/ghit.me

**Comment by liamjack** [comment]
Well yes I noticed, but has it been like this for a while or is it just temporary downtime ?

**Comment by KarelWintersky** [comment]
@liamjack , I've seen this bug for over a month now. I think, it is permanent

**Comment by liamjack** [comment]
Ok I'll remove that
