### ISSUE TITLE
Next step: separate logic to different files.

### ISSUE THREAD

**Issue by KarelWintersky** [PHPAuth/PHPAuth#301]
Like here : https://github.com/liamjack/PHPAuth

Why? 

We must implement different SESSION drivers : redis, mysql-storage, cookie-crypted.
We must implement different DB drivers: mysql, sqlite, redis (again)

so, more interfaces/implementations.
Lesser all-in-one code. 

When we embed code to project via composer, 'pack' all code to 1-2 files is not nessessary. 

What do you think about it?

**Comment by liamjack** [comment]
@KarelWintersky You're saying that my repo is a good example ? It's just basic database abstraction. 

What's the drive for session storage abstraction ?

I don't think this repo is worth the effort (of adding abstraction layers and more features), the code is seriously outdated.

**Comment by KarelWintersky** [comment]
You code is outdated, but code **organization** is interesting. 

> What's the drive for session storage abstraction ?

for storing sessions in Redis we can implement other driver-class. And call something like 
```
Session::store(...$args)
Session::check()
```
and so on.

In our config we will define storage method (with connection values to redis-server) and our class will use it inside.
