### ISSUE TITLE
Logout.

### ISSUE THREAD

**Issue by onlysli** [PHPAuth/PHPAuth#303]
The "logout" method need a parameter: $hash (User's session hash), but there is no public method to get the $hash. How can i make the user logout?

**Comment by KarelWintersky** [comment]
```
$session_hash = $auth->getSessionHash();
$auth_result = $auth->logout($session_hash);
```

**Comment by onlysli** [comment]
Thanks, it works.
That method wasn't in wiki.

**Comment by KarelWintersky** [comment]
Our wiki is outdated :(

**Comment by vktechnology** [comment]
$auth->getSessionHash();

This method is not exist any more
Which method should we use  ?
