### ISSUE TITLE
Unable to resend activation request not received

### ISSUE THREAD

**Issue by laurin1** [PHPAuth/PHPAuth#307]
Maybe I am missing something, but in my testing used resendActivation for an activation that had expired. I did not receive that activation email (probably due to incorrect SMTP configuration). Now when I try to resend, I get the "reset_exists" message. How do I make it resend that email?

**Comment by laurin1** [comment]
FYI, I ended up writing my own process to get the token and then used do_SendMail to re-send it, but seems like that process is missing from this library.

Thanks for all the hard work, BTW.

**Comment by KarelWintersky** [comment]
confirmed

**Comment by KarelWintersky** [comment]
solved somewhere here: cc333485fc65e96a07e81e6198487b8916367974

fixed returned messages.

See also, `request_key_expiration` setting in `phpauth_config` table

**Comment by KarelWintersky** [comment]
Fixed returned messages.

**Comment by laurin1** [comment]
Can you clarify how this is fixed, please? What does "fixed returned messages" mean?

**Comment by KarelWintersky** [comment]
We have two messages. 
```
$lang['reset_exists'] = "A reset request already exists. Next reset password request will available at %s";            
$lang['activation_exists'] = "An activation email has already been sent. Next reactivation will available at %s";
```

Before commit b5cca35a3ba522d99e05872027a25072796b65ee first message returned ALWAYS . It was a bug, of course. 

Now you will recieve 'reset_exists' message if you already requested password reset in last 10 mins (see `Config::request_key_expiration`) and 'activation_exists' if you already requested activation account.

Sorry for poor english.
