### ISSUE TITLE
Check if logged in on login page

### ISSUE THREAD

**Issue by m-menon** [PHPAuth/PHPAuth#308]
Thanks for this useful class. A quick question if I may ( I did scour for a complete example but what I found was discrete bits and pieces )
On the login page, if I want to check if there is a user logged in, would I be using one of these methods at the top of the page and if it returns true, then just forward them to the protected content? If yes which one would it be?

`getCurrentUID`
or
`getCurrentUser`

Thanks

**Comment by kungknut** [comment]
Hi!

Why don't you want to use the isLogged() method? This method returns true if the user is logged in, or false in any other case.

**Comment by m-menon** [comment]
Oops, is there a method called "isLogged()"? Don't remember having seen in the class [methods](https://github.com/PHPAuth/PHPAuth/wiki/Class-Methods)

**Comment by kungknut** [comment]
Seems like it is missing in there, in fact, it seems like more are missing.

Tip: have a look in the source code if you don't find what you are looking for in the wiki. The methods are explained there too.

**Comment by m-menon** [comment]
Cool thanks, let me check it out

**Comment by m-menon** [comment]
Cool thanks let me check it out
