### ISSUE TITLE
Wiki is outdated

### ISSUE THREAD

**Issue by kungknut** [PHPAuth/PHPAuth#309]
It seems like the wiki is outdated and many methods missing in there.

**Comment by KarelWintersky** [comment]
I know, sorry :(

**Comment by cliambrown** [comment]
Hi, I went through the source code and made an attempt at updating the 'Class Methods' page of the wiki. My new version is attached!

[Class Methods.txt](https://github.com/PHPAuth/PHPAuth/files/2290437/Class.Methods.txt)

**Comment by cliambrown** [comment]
Great, here's another version with a table of contents and an accidental duplicate method removed.

[Class Methods.txt](https://github.com/PHPAuth/PHPAuth/files/2290576/Class.Methods.txt)

**Comment by Conver** [comment]
@cliambrown - Thanks for trying to give me virus.

**Comment by Conver** [comment]
@cliambrown - Thanks, I'll go thru it.

**Comment by Conver** [comment]
@cliambrown - So the first one you sent, I can just delete that, or what is the different between those two files?

**Comment by cliambrown** [comment]
Yep, you can delete the first one! It had one method twice by mistake, and it doesn't have the TOC.

**Comment by Conver** [comment]
Great, later if I approve (I don't see why I wouldn't), I can make you a part of this project and you can go ahead and update things yourself, how about that?

**Comment by cliambrown** [comment]
Sounds good!

**Comment by Conver** [comment]
Status?
