### ISSUE TITLE
A system error has been encountered. Please try again.

### ISSUE THREAD

**Issue by iScripters** [PHPAuth/PHPAuth#31]
When calling
```
$rtn = $auth->register($_POST['email'], $_POST['firstpass'], $_POST['secondpass']);
```

Can't seem to figure out what is causing this error. Any way to properly debug?

**Comment by cuonic** [comment]
I debug this kind of error by adding an incrementing number to every `$return['message'] = "system_error";` so it becomes `$return['message'] = "system_error_3";`.

 Obviously this is not a way to properly debug, will add error codes some time soon. What method are you using ?

**Comment by iScripters** [comment]
Thanks for your reply. I am using register, editted my first post :)

**Comment by iScripters** [comment]
Update: Used your method and found out error '010' was causing this, which is
```
if(!$mail->send()) {
			$return['message'] = $this->lang["system_error"].'010';
			return $return;
		}
```

**Comment by cuonic** [comment]
You have a problem with PHP's sendmail or your SMTP settings, is sendmail installed on the server ?

**Comment by cuonic** [comment]
Added system error codes to the class with commit ea072652d5b0183b78ce18cbc2c07986aca37bf9 and added the corresponding [wiki page](https://github.com/PHPAuth/PHPAuth/wiki/System-error-codes).

**Comment by iScripters** [comment]
Sorry, should have updated my post. After knowing what caused the error (sending the mail) it only took me 2 minutes getting it to work. Well, after fixing an mcrypt error (error in my setup, libmcrypt wasn't installed on the server).

**Comment by cuonic** [comment]
Forgot to mention mcrypt in the requirements, added with commit 46e3e6f9804f3415fc839360e9f49a1d611b019b. Thanks for your feedback.
