### ISSUE TITLE
Any way to delete user without password?

### ISSUE THREAD

**Issue by Zeeraa** [PHPAuth/PHPAuth#310]
Im making a project where admins can delete other users accounts but i need to run `deleteUser` without a password for that to work. is there any way around this or should i just modify Auth.php to be able to do this

**Comment by Zeeraa** [comment]
And why is `updateUser` protected

**Comment by KarelWintersky** [comment]
Thank you for this issue.

**Comment by KarelWintersky** [comment]
Current implementation of useful functions is NOT effective :( 
Need a lot of work :(

**Comment by KarelWintersky** [comment]
See method 
```
deleteUserForced($uid)
```
