### ISSUE TITLE
Default null value for $isAuthenticated

### ISSUE THREAD

**Issue by PL404** [PHPAuth/PHPAuth#313]
In Auth.php at line 36, shouldn't the default value for $isAuthenticated be NULL rather than FALSE?

    /**
     * Public 'is_logged' field
     * @var bool
     */
    public $isAuthenticated = FALSE;

**Comment by KarelWintersky** [comment]
confirmed

**Comment by SauL182** [comment]
But inside if, $this->isAuthenticated should be checked if is FALSE not if is NULL or it will return always FALSE

    /**
     * Returns is user logged in
     * @return boolean
     */
    public function isLogged() {
        if ($this->isAuthenticated === FALSE) {
            $this->isAuthenticated = $this->checkSession($this->getCurrentSessionHash());
        }
        return $this->isAuthenticated;
    }

**Comment by jasonrush** [comment]
In my initial testing, it looks like just SauL182's change seems to make authentication function for me. Note I'm just starting to look into this library, so I don't have an extensive knowledge or testbed.

**Comment by KarelWintersky** [comment]
confirmed.
