### ISSUE TITLE
Use in api

### ISSUE THREAD

**Issue by iranappo** [PHPAuth/PHPAuth#315]
Hi
Can i use this library in my api?
My api is for android application and when user login into app,i want to use your library
Maybe?

**Comment by KarelWintersky** [comment]
You can try. 

Our license is MIT 

https://github.com/PHPAuth/PHPAuth/blob/master/LICENSE

**Comment by iranappo** [comment]
No i mean can use this for user’s login or only i can use for limi methods?

**Comment by Conver** [comment]
You can use it for your android app as an api, I have done that before.

søn. 22. jul. 2018 1.20 PM skrev iranappo <notifications@github.com>:

**Comment by iranappo** [comment]
So it is good
We use oAuth2 for user login and limit function and this combination is good
Thanks

**Comment by Conver** [comment]
When you are finish, maybe you can share an example with us? So we can put
it in our wiki so other users can see that it can be used.

søn. 22. jul. 2018 7.00 PM skrev iranappo <notifications@github.com>:
