### ISSUE TITLE
PHP 5.6

### ISSUE THREAD

**Issue by KarelWintersky** [PHPAuth/PHPAuth#317]
PHP 5.6 security support will ended at **31 Dec 2018** 

So, we well rewrite PHPAuth code to PHP 7. 

Be accurate.

**Comment by KarelWintersky** [comment]
http://php.net/supported-versions.php

PHP 5.6 support is ended.

**Comment by liamjack** [comment]
PHP 7.0 support has also ended, we can jump directly to 7.1

**Comment by louis123562** [comment]
Why not 7.2?

**Comment by liamjack** [comment]
7.1 is still supported for security fixes until 1 Dec 2019. Although I'm not against going straight to PHP 7.2, but when making these decisions you have to keep in mind users' that don't necessarily control the PHP version installed on the server (shared hosting for example).

This is also interesting: https://seld.be/notes/php-versions-stats-2018-1-edition

**Comment by KarelWintersky** [comment]
>Why not 7.2?

PHP 7.2 is good, but Debian 9 Stretch have only PHP 7.0 in stable. 

P.S. Why not PHP 7.3? 7.4 ? :-D
