### ISSUE TITLE
A system error has been encountered. Please try again. #03

### ISSUE THREAD

**Issue by aktiwers** [PHPAuth/PHPAuth#318]
After moving my project to a new server, I keep getting this error #03.
It happens when I do a : 
```
$mysql = new Mysql();
$dbh =$mysql->db;
$config = new PHPAuth\Config($dbh);
$auth = new PHPAuth\Auth($dbh, $config, $lang);

$register = $auth->register($_POST['username'], $_POST['password'], $_POST['password2']);
```
I'm not at the newest version of PHPAuth, but an exact same copy is running on another server and working fine. I tried updating to the latest version of PHPauth, but get the same error.

On the new server the PHP version is slightly newer (5.6.37) than the server its working on (5.6.30) - I even tried PHP 7.0, PHP 7.1 and PHP 7.2 - but they give me more errors.

I can see the error is thrown in Auth.php line 523 
`if(!$query->execute()) {
			$return['message'] = $this->lang["system_error"] . " #03";
			return $return;
}` 

Any idea why this is happening and how to fix it? 

Edit:
I also tried the 2 solutions suggested here: https://github.com/PHPAuth/PHPAuth/issues/291
But they did not fix it - still the same error :/

**Comment by kungknut** [comment]
Hi!

It is recommended to connect to the database using PDO.

It seems the credentials for the database are missing, are you able to interact with the database using any other functions in this library?

Also it seems you have not defined the $lang variable before using it when declaring $auth.

**Comment by aktiwers** [comment]
Thanks for the reply kungknut.

The strange thing is I am connecting to the database with PDO - the other functions in Auth.php are working.

Doing this works fine:
```
$mysql = new Mysql();
$dbh =$mysql->db;
$config = new PHPAuth\Config($dbh);
$auth = new PHPAuth\Auth($dbh, $config, $lang);

$login = $auth->login($_POST['email'], $_POST['password'], 1);
```
It's only the $auth->register function that produces this error. 

Could it be something in my server config that is not working? An exact copy of the project is running at another server, and does not produce the error.  

This is how my mysql class is connecting to the DB - all the functions in this class works fine as well. This is where I get the $dbh variable from.
```
class Mysql
{
protected $dsn;
protected $username;
protected $password;
public $db;

	
	function __construct()
	{
		include 'config.php';
		$this->dns= $configDns;
		$this->username= $configUsername;
		$this->password= $configPassword;
		$this->db = new PDO($this->dns, $this->username, $this->password);
	}
// lots of functions below...
```
But again, it is working on another server - so I was wondering if the register function needs some kind of server setting to work?

**Comment by aktiwers** [comment]
Here is another example of the other functions working, only register does not work:
```
echo '<pre>';
	$config = new PHPAuth\Config($dbh);
	$auth = new PHPAuth\Auth($dbh, $config, $lang);
	$login = $auth->login('me@gmail.com', 'somepassword', 1);
	print_r($login);
	$register = $auth->register('youfail@gmail.com', 'tEmPP4assWord', 'tEmPP4assWord');
	print_r($register);
	$uid  = $auth->getUID('me@gmail.com');
	print_r($uid);
	$change = $auth->changeEmail($uid,'me2@gmail.com', 'somepassword');
	print_r($change);
```
The output of this:

> Array
> (
>     [error] => 
>     [message] => You are now logged in.
>     [hash] => 7c7900e18f65d896812ca15a48087fdc3884b699
>     [expire] => 1796122323
> )
> Array
> (
>     [error] => 1
>     [message] => A system error has been encountered. Please try again. #03
> )
> 17Array
> (
>     [error] => 
>     [message] => Email address changed successfully.
> )

And the email is changed. But the user is not registered.. :/

Please let me know if I can provide any other info to help solve the issue!

**Comment by KarelWintersky** [comment]
Check your database struct.
Something like: `SHOW CREATE TABLE phpauth_users` from mysql console.

**Comment by KarelWintersky** [comment]
Show your `$configDns`

**Comment by KarelWintersky** [comment]
I think, your have issue here:
```
$query = "INSERT INTO {$this->config->table_users} (isactive) VALUES (0)";

        $query_prepared = $this->dbh->prepare($query);

        if (!$query_prepared->execute()) {
            $return['message'] = $this->__lang("system_error") . " #03";
            return $return;
        }
```

**Comment by Conver** [comment]
Just a quick note:

People have been having these issues before, they fixed it by adding auto increment to the id field in the user table. Some times some DB servers doesn't add it and it gives problems with register, please check that auto increment is added to id field.

**Comment by aktiwers** [comment]
Thanks a lot for all the attention.

> mysql> SHOW CREATE TABLE users;
> +-------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
> | Table | Create Table                                                                                                                                                                                                                                                                                                                                                  |
> +-------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
> | users | CREATE TABLE `users` (
>   `id` int(11) NOT NULL AUTO_INCREMENT,
>   `email` varchar(100) DEFAULT NULL,
>   `password` varchar(60) DEFAULT NULL,
>   `isactive` tinyint(1) NOT NULL DEFAULT '0',
>   `dt` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
>   `username` varchar(255) NOT NULL,
>   PRIMARY KEY (`id`)
> ) ENGINE=InnoDB AUTO_INCREMENT=55 DEFAULT CHARSET=utf8 |
> +-------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
> 1 row in set (0.00 sec)
> 

Here are the variables from my Mysql class:
// Mysql Info
```
$configDns= 'mysql:dbname=PEAQS;host=localhost;charset=utf8';
$configUsername= 'root';
$configPassword= 'rootpassword';
```

I tried changing the first part of the addUser function as suggested by KarelWintersky but I still get the "#03" error.

Isn't it strange that it works perfectly fine on another server? I simply copied my project, exported the MySQL database, imported it to the new server. Its a clean new server that I just setup, that is why I was thinkinig it could be a server config error.

But strange that changeEmail() works and writes the new email to database, when registrer() keeps throwing this error.

**Comment by KarelWintersky** [comment]
try execute 
`INSERT INTO users (isactive) VALUES (0)` in your mysql console.

Then print your:

- Mysql version
- PHP Version?
- list of installed php extersions?

**Comment by aktiwers** [comment]
Yay! Thanks a lot KarelWintersky. It was because the "username" field in "users" did not have a default value.

> mysql> INSERT INTO users (isactive) VALUES (0);
> ERROR 1364 (HY000): Field 'username' doesn't have a default value
> mysql> INSERT INTO users (isactive) VALUES (0);
> Query OK, 1 row affected (0.02 sec)

I then changed it to have a default value, re-ran the registrer() function and it now created my user!

> Array
> (
>     [error] => 
>     [message] => Account created.
> )

Thanks a lot for help

**Comment by KarelWintersky** [comment]
May I close issue? :)

**Comment by aktiwers** [comment]
Yes, thanks a lot :)
