### ISSUE TITLE
reCAPTCHA dependency

### ISSUE THREAD

**Issue by rowan-m** [PHPAuth/PHPAuth#319]
You have `google/recaptcha` as a dependency. I've recently updated this with a `1.2` release. It *should* be backwards compatible, but obviously you'd want to test that. Happy to respond to issues over at https://github.com/google/recaptcha

**Comment by KarelWintersky** [comment]
@rowan-m , Thank you! We will check as soon as possible!

**Comment by Conver** [comment]
Status?
