### ISSUE TITLE
checkCaptcha vs checkReCaptcha methods

### ISSUE THREAD

**Issue by cliambrown** [PHPAuth/PHPAuth#321]
I noticed that the `checkReCaptcha()` method only returns true, but it is being used by multiple other methods. Is it meant to be replaced by the `checkReCaptcha()` method?

**Comment by Conver** [comment]
It returns true by default if people doesn't want to use it, if they want to use it, they can use the code in the readme: https://github.com/PHPAuth/PHPAuth#captcha-implementation

**Comment by cliambrown** [comment]
Thanks, sorry I missed that!
