### ISSUE TITLE
Multiple active sessions for same user

### ISSUE THREAD

**Issue by bletham** [PHPAuth/PHPAuth#326]
Thanks for the great project!

I have a question about having multiple active sessions for the same user. If I log in on one device (A), and then log in on a second device (B), logging in on B ends the session on A.

This seems to be happening here: https://github.com/PHPAuth/PHPAuth/blob/master/Auth.php#L430

Is there a reason for this behavior? If I want to be able to be logged in on multiple devices at the same time can I simply comment out that line, or are there other considerations / a better way?

**Comment by KarelWintersky** [comment]
I think, we must make it optionable via config. 

Write this code if you want and then make PR. 

Thank you.
