### ISSUE TITLE
Question about IP check

### ISSUE THREAD

**Issue by bletham** [PHPAuth/PHPAuth#330]
In checkSession we check if the IP address of the request matches that stored for the cookie in the db, and do not return a valid session if it doesn't match:
https://github.com/PHPAuth/PHPAuth/blob/master/Auth.php#L543

Is this intended to mitigate cookie theft?

If that is the purpose, should we also delete the session if there is an IP mismatch?

If I understand this logic correctly, then it means that in case of a dynamic IP the user will effectively be logged out when their IP changes. Since there is little chance of them returning to their original IP, it again seems reasonable to delete the session.

If that seems right to you all I can make a PR for it.

**Comment by Conver** [comment]
Feel free to make an PR.

**Comment by seularts** [comment]
Has there been a solution for this presented? I am curious as well.

**Comment by louis123562** [comment]
I think we should handle the new behaviour with an configuration entry, so everyone can decide on his own what happens. For me and my PHPAuth usings, it is not necessary at the moment.

**Comment by Conver** [comment]
status?

**Comment by bletham** [comment]
Sorry, I had gotten PHPAuth all working nicely for the application I was building and got distracted by other things. My php development environment isn't set up anymore but I can try to get this done this weekend.

**Comment by Conver** [comment]
@bletham How goes?

**Comment by bletham** [comment]
Sorry for the long delays, I don't think I'll be able to get to this in the next few months so I'll just close this since I don't think it's a critical feature.
