### ISSUE TITLE
Stub Project to Compliment Wiki

### ISSUE THREAD

**Issue by eagletommy52** [PHPAuth/PHPAuth#331]
Awesome work!  Would it be possible to add an example project with the bare bones functionality (login page, signup page, login restricted page) to help junior folks see how to use class methods within the context of a PHP project.  I started to stub out such a project here https://github.com/eagletommy52/PHPAuth-Example-Project, but I'm pretty junior and wasn't sure how to properly implement the login/register methods on a processor.

**Comment by KarelWintersky** [comment]
You can't commit to project directly.

Fork, edit, commit and make pull request.
