### ISSUE TITLE
Where is getSessionHash function  ?

### ISSUE THREAD

**Issue by vktechnology** [PHPAuth/PHPAuth#334]
I want to to make logout  and unable to find user session hash function  before it was  "getSessionHash"
----------------------------------------
$config = new PHPAuth\Config($dbh);
$auth   = new PHPAuth\Auth($dbh, $config);    

$auth->logout($hash)

Which method to get  $hash ?  
Before it was method name getSessionHash()

**Comment by vktechnology** [comment]
Hi

I got the answer
this method changed to getCurrentSessionHash()

**Comment by kungknut** [comment]
How about backwardscompatibility?

```
getSessionHash() {
    return getCurrentSessionHash();
}
```

**Comment by louis123562** [comment]
I always store the hash manually - is it wrong ?

**Comment by vktechnology** [comment]
I just added to WIKI

## getCurrentSessionHash 
Description: Get current user's session hash

Parameters:
Void

Returns:
$hash (string): Current user's session hash 
false (boolean): False if no cookie

**Comment by louis123562** [comment]
Thanks :)
