### ISSUE TITLE
Non-transactional registration

### ISSUE THREAD

**Issue by Robin-Murison** [PHPAuth/PHPAuth#335]
Hi, 

**INTRODUCTION**
I have problems with AddUser not updating the initially non-active user. One it does not always work and for me it now never works and secondly it should be an SQL transaction.

**FLAME ALERT skip if you want to:**
First, a comment an API is only as good as its documentation.  The only reliable documentation of PHPAuth is the code as there are so many forks of it. Some quite well documented but often with different function names. Correct documentation is essential to make any API worth working with,

**Logging class overview**
e.g. As a newby I was not clear how the error reporting works. It appears to echo to my PHP pages which completely breaks my redirection that uses header() and text on the page before the headers stops them working.

So I added Logging to a database on my local machine to find out what was happening because I do not understand how to get the existing error reporting to work with out spewing to the page. So I had to reinvent the wheel.  

**Logging class integration work I could do.**
I have not documented it or tried to integrate it, as doing so I would need to integrate it a lot further into the already existing error handling code. As I have __FILE__ and __LINE__ especially useful in my debugging this would be a breaking change. That I do not have the time nor the money to add. If you want a copy of Logging.php class I could upload it to master but it should get the logging table name from Config. 

**The issues with AddUser**
I have had serious problems with AddUser not updating the initially non-active user. One it may not always work and for me it now never works and secondly it should be an SQL transaction. It should not rely on the mechanics of PHP. SQL and PHP should be kept as distinct as possible to minimize confusion and in this case to get it to work.

The Problem Code in phpauth/Auth.php:
function addUser(...){
        $this->log->Verbose(__FILE__,__LINE__, 'addUser', 'entrance');
        $return['error'] = true;
        $query = "INSERT INTO {$this->config->table_users} (isactive) VALUES (0)";
        $query_prepared = $this->dbh->prepare($query);
        if (!$query_prepared->execute()) {
            $this->log->Error(__FILE__,__LINE__, 'addUser', $query . ' failed');
            $return['message'] = $this->__lang("system_error") . " #03";
            return $return;
        }
        $this->log->Verbose(__FILE__,__LINE__, 'addUser', $query . ' succeeded');
        $uid = $this->dbh->lastInsertId("{$this->config->table_users}_id_seq");
...  // email activation and errohandling logic
        $query = "UPDATE {$this->config->table_users} SET email = ?, password = ?, isactive = ? {$setParams} WHERE id = ?";
        $query_prepared = $this->dbh->prepare($query);
        $bindParams = array_values(array_merge(array($email, $password, $isactive), $params, array($uid)));
        $this->log->Debug(__FILE__,__LINE__, 'addUser', 'About to update user to valid data, query:'. $query. 'Parameters: '. var_export($bindParams, true));
        $this->log->Debug(__FILE__,__LINE__, 'addUser', 'About to update user to valid data, query:'. $query. 'Parameters: '. var_export($bindParams, true));
        if (!$query_prepared->execute($bindParams)) {
            // update always succeeded to update 0 records because the Id's do not match
            $this->log->Error(__FILE__,__LINE__, 'addUser', 'Update user to valid data Failed');
            $query = "DELETE FROM {$this->config->table_users} WHERE id = ?";
            $query_prepared = $this->dbh->prepare($query);
            $this->log->Error(__FILE__,__LINE__, 'addUser', 'about to delete null user');
            if (!$query_prepared->execute(array($uid)));
            {// New error check that was never called
                $this->log->Error(__FILE__,__LINE__, 'addUser', 'failed to delete null user');
                $return['message'] = $this->__lang("system_error") . " #99";
                return $return;
            }
            $return['message'] = $this->__lang("system_error") . " #04";
            return $return;
        }
        $return['error'] = false;
        $this->log->Debug(__FILE__,__LINE__, 'addUser', 'Update user to valid data succceeded');
        return $return;
}

Initially I had issues with SMPT activation but that is now sorted. 

During which time the line: $return['message'] = $this->__lang("system_error") . " #03";
was called every other registration.  That happens after a failed: INSERT INTO {$this->config->table_users} (isactive) VALUES (0);
It failed every other time. If I deleted the row manually it then worked the next time.
The email activation just crashed. As I have said that is now sorted.

However, I may have messed up something else because I never got to the rest of the code, which  should have tidied this up for me. 
Specifically:
$uid = $this->dbh->lastInsertId("{$this->config->table_users}_id_seq");
is now giving very odd results.

The $uid returned is a value well over 300 and the actual Id in the record was 17 on my last test before writing this. They do not match. So, the UPDATE query succeeds to update nothing. This is very undirable.

First bad effect: The full user is never inserted and is left with null values.

Second side effect: Because the update succeeded the delete for an unsuccessful update never happens and I have to delete it manually.

I an unclear why: $uid = $this->dbh->lastInsertId("{$this->config->table_users}_id_seq");
is giving the wrong answer. 

I have added extra parameters into the table, which should never be null and I have not set a default for them. So personally I am surprised the initial insert works at all and should at least set those additional parameters regardless of what PHPAuth needs to avoid that problem.

There are two issues. for whatever reason:
1. $uid = $this->dbh->lastInsertId("{$this->config->table_users}_id_seq");
is not returning the last id inserted. 

**Pontential fix**
You can change your SQL query so that it is guaranteed to only update the last record e.g.:
$query = "UPDATE {$this->config->table_users} SET email = ?, password = ?, isactive = ? {$setParams} ORDER BY `id` DESC LIMIT 1"

When you only rely on SQL it is guranteed to work. Keeping the separation between mysql and PHP cleaner guarantees that you are updating 1 and only one record, The existing condition already there could change 0 or 1 records in my case it is now always 0.

**The main issue**
2. There is an even bigger issue is that this process is not a transaction. On any enterprise ready solution you could have more than one person registering at the same time. This whole process needs to be rethought out using a transaction. Without a transaction even if this code did work as expected if two people were registering at the same time then there could be two blank recors added and then both users update the last record and a blank user and the later arrival are inserted but both report success.

A different solution if you do not like transactions, I do not see why you would not, is to add a specific unique hash in the initial insert and then find the id by the unique hash. Then continue from there.

Having read this code has put me right off PHPAUth as a secure authenticator. These issues concern me enough not to use it, In fact I cannot without fixing these issues and if I fix them I should update master to save other people from these issues.

**Reason for posting**
As it is this has cost me more than a week of effort. to get this far, I cannot afford to waste anymore time or money on it. Rather than righting this off as a complete waste of time. I thought I ought to let you know what problems I have found so that someone who has spare time or is paid to fix them, can fix them.

Having looked at this code has not instilled confidence in me.

**Comment by KarelWintersky** [comment]
Brevity is the soul of wit.

**Comment by louis123562** [comment]
I do register over a 100 people at the same time sometimes, and there has never been an error or an other problems yet.

I won't change the running code...
