### ISSUE TITLE
E-Mail addresses with german Umlaut's are not valid

### ISSUE THREAD

**Issue by louis123562** [PHPAuth/PHPAuth#336]
Hey,

when registering a new user, the function validateEmail($email) proofs the given mail with:

elseif (!filter_var($email, **FILTER_VALIDATE_EMAIL**)) {
            $state['message'] = $this->__lang("email_invalid", $email);

            return $state;
        }

so if try to use this address: p.l**ä**cker@testmuster.de it fails. 

**FILTER_VALIDATE_EMAIL** uses the RFC 822, in which umlauts are not specified.
 http://php.net/manual/en/filter.filters.validate.php (third entry)

So, do you have a solution for this ? We could try to use a REGEX or something like that to proof the address.

Thank you in advance, Louis :)

**Comment by Conver** [comment]
I'll look into this next week.

**Comment by KarelWintersky** [comment]
**Internet E-mail address format (RFC 822)** 

( http://jkorpela.fi/rfc/822addr.html )

Valid characters in email are: 
```
!"#$%&'*+-/0123456789=?
@ABCDEFGHIJKLMNOPQRSTUVWXYZ^_
`abcdefghijklmnopqrstuvwxyz{|}~
```

Your email address `p.läcker@testmuster.de` is **NOT VALID**. 

If any DE server supports your email - it violates RFC.
