### ISSUE TITLE
Translate is broken? or what I am doing wrong?

### ISSUE THREAD

**Issue by Prospection** [PHPAuth/PHPAuth#337]
Have updated from composer my 8+ month old code, and released something is changed :) 
Tried main branch also.

`<?
//`composer require phpauth/phpauth:dev-master`

require_once 'vendor/autoload.php';

use PHPAuth\Config as PHPAuthConfig;
use PHPAuth\Auth as PHPAuth;

$dbh = new PDO("mysql:host=localhost;dbname=k", "root", "111");

$config = new PHPAuthConfig($dbh,'', '','ru_RU');
$auth = new PHPAuth($dbh, $config,'ru_RU');

$a = $auth->login('111', 111111, true);
print_r($a);
`
getting English: Array ( [error] => [message] => You are now logged in.

**Comment by KarelWintersky** [comment]
Таблицу с переводами в базу импортировал?

**Comment by Prospection** [comment]
> Таблицу с переводами в базу импортировал?

Нет, а разве они уже не берутся из файлов?
Если нет, подскажите как импортировать. 
Спасибо!

**Comment by KarelWintersky** [comment]
Настройки хранятся или в  `database_mysql.sql` (по умолчанию) или в конфиге. 

Конфигом может быть json или  ini  файл или сразу PHP Array с данными. Структура идентична.

database_translation_dictionary.sql - словарь переведенных сообщений. Если его нет - подставляются английские сообщения по умолчанию. 

Импортировать - mysql -u .. -p ... --database ... < file.sql

**Comment by kungknut** [comment]
I notice you are communicating in Russian. When you have solved the problem or whatever it may be. I think it would be nice if one of you could summarize the solution in English so that other non-russian people also can benefit from the information.

Regards

**Comment by Prospection** [comment]
> I notice you are communicating in Russian. When you have solved the problem or whatever it may be. I think it would be nice if one of you could summarize the solution in English so that other non-russian people also can benefit from the information.
> 
> Regards

Of course, i thought to do this and definitely I will.

**Comment by Prospection** [comment]
Ok, here is what happened. 

I have updated my year old installation from composer - and lost my RU translation.
As a dear Mr. Karel from the Greatest city on the Neva-river suggested - I have imported sql file database_translation_dictionary.sql (/vendor/phpauth/phpauth/database_defs), and my translation working now.

I feel sorry for disturbing you folks, but year ago version worked out of php files, and I obviously didn't have this table in my installation.

Upgrade process from my old version is not reflected in manual and I guess it's not really necessary. If someone would meet the same problem they will find my post.

**What is really need to be fixed is adding translation to key "account_not_found"** Because It seems lost from translation.

Thanks a lot to anyone who contributed to this nice project!

**Comment by louis123562** [comment]
I had the same problems in spring. According to the errors i recieved i was able to fix it, but i also think it is important to write in a common language. Thank you for translating it :)

Do we have a changelog for the masterbranch ?

**Comment by KarelWintersky** [comment]
I am looking for good multi-translating engine - with parallel translation.

**Comment by louis123562** [comment]
https://docs.transifex.com/projects/open-source-project

If i understand correctly, we can use transifex for OpenSource Projects. Maybe someone else can have a look at it.

**Comment by Conver** [comment]
Status?
