### ISSUE TITLE
Registration - Error: A system error has been encountered. Please try again. #03

### ISSUE THREAD

**Issue by brimacbain** [PHPAuth/PHPAuth#338]
Hi all,

Ran into an issue registering when I moved from my dev environment to production.

When I go to register using:
$register = $auth->register($_POST['email'], $_POST['password'], $_POST['repeatpassword']);

I get back:
Error: A system error has been encountered. Please try again. #03

I think it's getting stuck at addUser when it prepares/executes:
$query = "INSERT INTO {$this->config->table_users} (isactive) VALUES (0)";
$query_prepared = $this->dbh->prepare($query);

Site is running PHP 5.6.38 and MariaDB 10.2.17- everything works fine in my xampp development environment, and everything else on production site works fine except registration (I can update passwords, login etc as usual).

Anyone have any thoughts on this?  Loving using PHPAuth so far btw!

Thanks for your help!

**Comment by Conver** [comment]
First, you should update your PHP to the newest version.

Second, check your users table and they the id has auto increment.

**Comment by brimacbain** [comment]
No problem- it's actually running 7.2 already, disregard the old version I mentioned (not sure where that came from now).

Users table looks good- id is set to auto increment.

It registers fine in my dev environment, but it's still not working on production.  I'll keep poking around!

**Comment by louis123562** [comment]
https://github.com/PHPAuth/PHPAuth/wiki/System-error-codes

#03: (addUser) Failed to insert new row into users table

-> Did you change your database connection string ?
-> Did you updated PHPAuth to the current master-branch ?
-> I guess it has something to do with your database. Can you try to insert some simple data (not in reference to PHPAuth) into a different database ? You could try to surround the execution with a try catch to get database-error string - so you will notice if there is a general problem.

**Comment by KarelWintersky** [comment]
Looks like a problem with your database.
Try execute `INSERT INTO  (isactive) VALUES (0)` from your mysql console. Of course, replace `{$this->config->table_users}` to you real table_users.

**Comment by brimacbain** [comment]
Hi all,

First off, thanks for all your help!  I had added a custom row to the table to store some additional info, but hadn't set a default value and it was hanging on that.  I've given it a default value of null and now everything seems to be working- thanks for all your help everyone!

**Comment by Conver** [comment]
Which field needed a default value?
- So we can fix it in the code.

**Comment by brimacbain** [comment]
Ah sorry Conver, I meant column not row.  I added a custom column to the table for some data I'd be storing during registration, and that's what wasn't set to have a default value.  So it was nothing to do with PHPAuth, and everything to do with the setup of the additional column I'd put in!

**Comment by Conver** [comment]
Okay, cool :) Glad you worked it out :)

Closing.
