### ISSUE TITLE
How to deal with rapidly expanding Auto-incremen?

### ISSUE THREAD

**Issue by seularts** [PHPAuth/PHPAuth#375]
I'm looking at the attempts table for example, where there is a large volume of volatile data that gets added and deleted over time. A consequence of this is that the auto-Increment for the primary key grows as well very fast, how do you recommend I handle this?

**Comment by KarelWintersky** [comment]
set type of field as BIGINT.

**Comment by louis123562** [comment]
I don't think, that using a numeric, upcounting ID is correct for your needs.

Have a look at https://en.wikipedia.org/wiki/Universally_unique_identifier

**Comment by seularts** [comment]
Wow, this is clever. But also seems a bit overwhelming to implement. Could I maybe escape with this function to satisfy the uniqueness:

class UUID {

  public static function v4() {
    return sprintf('%04x%04x-%04x-%04x-%04x-%04x%04x%04x',

      // 32 bits for "time_low"
      mt_rand(0, 0xffff), mt_rand(0, 0xffff),

      // 16 bits for "time_mid"
      mt_rand(0, 0xffff),

      // 16 bits for "time_hi_and_version",
      // four most significant bits holds version number 4
      mt_rand(0, 0x0fff) | 0x4000,

      // 16 bits, 8 bits for "clk_seq_hi_res",
      // 8 bits for "clk_seq_low",
      // two most significant bits holds zero and one for variant DCE1.1
      mt_rand(0, 0x3fff) | 0x8000,

      // 48 bits for "node"
      mt_rand(0, 0xffff), mt_rand(0, 0xffff), mt_rand(0, 0xffff)
    );
  }

}

$v4uuid = UUID::v4();
echo $v4uuid;

**Comment by louis123562** [comment]
I store UUID's in MySQL Database as **varbinary(36)**.

To generate a UUID, i use this: 


```
    function guidv4()
    {
        if (function_exists('com_create_guid') === true)
            return trim(com_create_guid(), '{}');

        $data = openssl_random_pseudo_bytes(16);
        $data[6] = chr(ord($data[6]) & 0x0f | 0x40); // set version to 0100
        $data[8] = chr(ord($data[8]) & 0x3f | 0x80); // set bits 6-7 to 10
        return vsprintf('%s%s-%s-%s-%s-%s%s%s', str_split(bin2hex($data), 4));
    }

```

**Comment by seularts** [comment]
Oh, this is even better :) I'm not much of a database architect, so excuse my noobish question but is varbinary available in postgresql, mmslq, etc?

**Comment by liamjack** [comment]
There's actually no need for the id column, as we never need to manipulate a row alone. The table is used to log authentication attempts and count the number of attempts for a certain IP, nothing else.

What could be done, as well as removing the id column, is adding a cron job to purge expired attempts, even if daily it could help reduce the storage space used by the attempts table.

**Comment by seularts** [comment]
You are right. Since my attempts are based on IP alone with an extra column for counting how many attempts are left for a specific IP, I could simply make the IP column unique.

**Comment by louis123562** [comment]
Many roads lead to home - choose your's 👍

**Comment by seularts** [comment]
Thank you for your help guys!

**Comment by liamjack** [comment]
No that's not how it works, every time an authentication attempt fails, a new row is added to the table containing IP and an expiration date for the attempt. 

If you make the IP column unique then you will only be able to add one attempt per IP, which would cause an SQL error when you try to add a new attempt. 

The way it works is that every time the user tries to authenticate we take a look at how many rows exist in this table for that IP (that haven't expired), and if it's greater than 3, then we block the user from authenticating.

**Comment by seularts** [comment]
I know what you mean liamjack, I edited my table a bit so it updates the tries and the expiration date depending on various user behavior. I'm not implementing it like it was presented here. I have other actions attached to the remaining attempts value that I can easily manipulate this way.

**Comment by liamjack** [comment]
Oh ok, great !

**Comment by KarelWintersky** [comment]
@louis123562 , GUID is a BAD solution. 

Index on varbinary is slow.

**Comment by louis123562** [comment]
@KarelWintersky for my needs it is fast enough :p

**Comment by liamjack** [comment]
I have removed the `id` column on the `fix-attempts-table` branch

**Comment by Conver** [comment]
Good that you did it on another branch as we are actually a few that uses that ID field.

**Comment by liamjack** [comment]
@Conver What do you use the `id` field for specifically ?

**Comment by Conver** [comment]
Myself I use it as an identifier, so that I can manipulate rows by it's ID

I don't know what others use it for, but I know at least 5-6 people which uses it for something.

**Comment by liamjack** [comment]
Same as Issue #383, the PHPAuth code base does not require the ID column, if you want the column for your own needs, nothing is stopping you from keeping it / adding it on your side.

**Comment by KarelWintersky** [comment]
Better way for guids:

```
file_get_contents('/proc/sys/kernel/random/uuid')
```
warning, *nix only
