### ISSUE TITLE
Hash IP addresses stored in database ?

### ISSUE THREAD

**Issue by liamjack** [PHPAuth/PHPAuth#378]
IP Addresses can be PII (Personally Identifiable Information) and storing the cleartext value in the database is of no use to PHPAuth. Currently PHPAuth stores cleartext IP Addresses in the following places:

* `phpauth_attempts.ip`
* `phpauth_sessions.ip`

Instead we could store a hash of the IP address + site wide salt. This would mean that in case the database contents were stolen, the attacker would not be able to retrieve the original IP addresses. (This also requires storing the site wide salt outside of the database, aka in an `.env` file, which could possibly be auto-generated if not found on first run)

The same could also be done for User Agents, currently stored in cleartext in the `phpauth_sessions.agent` column.

What do you think ?

**Comment by Conver** [comment]
I'm already hashing IP and session info, so I'll say go for it.

**Comment by KarelWintersky** [comment]
PII? New European initiative?

**Comment by Conver** [comment]
Just remember that we need to make is backwards compatible.

@KarelWintersky - I don't think so, it's not something I've heard before. unless it's very new, or just himself using it :P

**Comment by liamjack** [comment]
@Conver The backwards compatibility could be hard, as I'm changing the column names (from `ip` to `ip_hash` and from `agent` to `user_agent_hash`) and I'm also changing the data type to `BINARY(16)` for efficient storage of an MD5 Hash.

Maybe an "upgrade script" could help by deleting all existing sessions and attempts, then changing the table structures, just a few lines of SQL to execute to upgrade, the only downside is that everyone will be logged out.

**Comment by liamjack** [comment]
MD5 remains fast, and the only real problems encountered involve collision attacks which are pretty unlikely to happen with IP + salt. It's not to late to change though, maybe SHA2 is more appropriate, the main goal is to keep the real IP from attackers.

**Comment by KarelWintersky** [comment]
Results of hashing & crypt algos (1 mil iterations)
```
Details:
- 0.982400 seconds for `fnv132`
- 0.998200 seconds for `fnv1a32`
- 1.047600 seconds for `adler32`
- 1.126100 seconds for `fnv164`
- 1.139400 seconds for `fnv1a64`
- 1.188800 seconds for `crc32b`
- 1.199600 seconds for `joaat`
- 1.256900 seconds for `crc32`
- 1.517200 seconds for `md5`
- 1.656500 seconds for `md4`
- 1.931000 seconds for `tiger128,3`
- 1.952300 seconds for `tiger160,3`
- 1.982500 seconds for `tiger192,3`
- 2.312800 seconds for `tiger128,4`
- 2.376700 seconds for `tiger160,4`
- 2.381800 seconds for `tiger192,4`
- 2.542500 seconds for `sha1`
- 3.305200 seconds for `ripemd128`
- 3.405300 seconds for `ripemd256`
- 3.876900 seconds for `sha3-256`
- 4.017400 seconds for `sha3-224`
- 4.211000 seconds for `haval128,3`
- 4.234200 seconds for `haval160,3`
- 4.265700 seconds for `haval192,3`
- 4.268700 seconds for `haval224,3`
- 4.298400 seconds for `haval256,3`
- 4.633000 seconds for `ripemd160`
- 4.719800 seconds for `ripemd320`
- 4.748400 seconds for `sha512/224`
- 4.762800 seconds for `sha512/256`
- 4.815200 seconds for `sha384`
- 4.871400 seconds for `sha512`
- 5.250200 seconds for `sha224`
- 5.273700 seconds for `sha256`
- 5.488900 seconds for `haval128,4`
- 5.523300 seconds for `haval160,4`
- 5.537200 seconds for `haval192,4`
- 5.553200 seconds for `haval224,4`
- 5.575500 seconds for `haval256,4`
- 6.348800 seconds for `haval128,5`
- 6.375200 seconds for `haval160,5`
- 6.397600 seconds for `haval192,5`
- 6.412600 seconds for `haval224,5`
- 6.438900 seconds for `haval256,5`
- 7.496600 seconds for `gost`
- 7.526500 seconds for `gost-crypto`
- 8.001100 seconds for `whirlpool`
- 10.76110 seconds for `snefru`
- 10.78410 seconds for `snefru256`
- 14.21790 seconds for `sha3-384`
- 14.26930 seconds for `sha3-512`
- 27.44900 seconds for `md2`
```
