### ISSUE TITLE
Create cron job for removing expired attempt logs

### ISSUE THREAD

**Issue by liamjack** [PHPAuth/PHPAuth#379]
The attempts table can get pretty full, as expired attempts *for a given IP address* are only removed when a client with the IP address performs an authentication attempt, calling the `isBlocked()` method.

This is pretty inefficient as the deletion query slows down the reply to the client's authentication request.

The same also applies for expired sessions, which are never purged from the sessions table.

I propose that a daily cron job deletes the expired attempts and sessions from the database.

**Comment by KarelWintersky** [comment]
it may be good solution for highload projects.

**Comment by Conver** [comment]
I like the idea as long as it's optimal, I myself like to keep the data on it, just by adding another field which marks the row deleted etc. I like keeping the data for some of my projects where some other project I'm doing wouldn't mind it being deleted.

But just a little note, if you db gets slow then you are not indexing right, most db's can handle laaarge tables on very small servers.

So yes, the cronjob idea is great, but even better would be looking into indexing etc as the db should be able to handle it unless we are talking 50+m rows.

**Comment by Conver** [comment]
Little side note: The reason I mark the row as deleted on some projects is because I want my users to be able to see wrong attempts for their account.

Plus some extra security steps I've added which some of it are based on the attempts table
