### ISSUE TITLE
Remove user agent column from database

### ISSUE THREAD

**Issue by liamjack** [PHPAuth/PHPAuth#383]
Partly discovered through #378, it seems that we store the user agent but it isn't used at all. Should we not remove this column since the information is not used ?

**Comment by Conver** [comment]
No. You might not be using it, but I am aswell as others.

And I KNOW that it is used by others for various checks and so on.

**Comment by liamjack** [comment]
I'm not using it and PHPAuth isn't using it at all with the current code base, so the information is useless, unless you modify the `Auth.php` class.

**Comment by louis123562** [comment]
I agree to liamjack, so that PHPAuth is not doing anything with it, it isn't necessary.
If you need it, you have to implement it yourself.
