### ISSUE TITLE
Question: Compatible user management library?

### ISSUE THREAD

**Issue by seularts** [PHPAuth/PHPAuth#385]
Is there a powerful library out there that manages users/admins with CRUD operations after they are logged in?

**Comment by louis123562** [comment]
What should this library manage?

**Comment by seularts** [comment]
A library where you can define user roles, such as admin/root and edit/delete/create/update/search new users or user-data. Something similar to wp-admin user levels.

**Comment by louis123562** [comment]
I dont know if your database can handle multiple users (some share servers cant), but in PHPMyAdmin you can set permissions for each user.

**Comment by seularts** [comment]
My server can handle multiple users :) Of course, I can edit users through PHPMyAdmin, but I would like to do it from the site itself not logging in cPanel. So, is there such a library that is secure and competent enough to do this task?

**Comment by KarelWintersky** [comment]
Is is only core of Auth engine.

You can implement CRUD for your project with SimpeRouter, any DB wrapper and PHPAuth.

**Comment by KarelWintersky** [comment]
And, mv PHPMyAdmin /dev/null

**Comment by seularts** [comment]
Thank you for the replies. Well, I don't want the whole functionality of PHPMyAdmin :D I guess I will just write my own little crud to deal with the users. I was just curious if there was a professionally done library out there like PHPAuth so I can follow some guidelines.

**Comment by junior333svk** [comment]
i would recommend to use

>  API Key

 as your default while you using your server.
