### ISSUE TITLE
Translation not working

### ISSUE THREAD

**Issue by m0lmk** [PHPAuth/PHPAuth#387]
I'm attempting to get the translation feature working but not having much luck.

This is what I have in my config...

    $auth = new PHPAuth($dbh, $config, "fr_FR");

But I am still returned error messages in English.

I've tried using `translation_source: php` and `translation_source: sql` in the database and have verified that the `phpauth_translation_dictionary` is in the database and that the php language files exist.

Can anyone point me in the right direction to debug why this won't work?

**Comment by louis123562** [comment]
$auth = new PHPAuth($dbh, $config); (thats the way how i instantiate a new object)

Did you set the 'site_language' in the 'phpauth_config'-table to fr_FR?

**Comment by m0lmk** [comment]
It seems that I had to set `$config = new PHPAuthConfig($dbh, '', '', 'fr_FR');` to get it to work.

All ok now.

Thanks.

**Comment by louis123562** [comment]
https://phpauth.github.io/PHPAuth/#custom-config-sources

-> there is a parameter list
