### ISSUE TITLE
Several privacy/usability issues

### ISSUE THREAD

**Issue by m0lmk** [PHPAuth/PHPAuth#388]
I've been using PHPAuth for a few weeks and there seem to be a few small privacy/usability issues that would be good to address.

They generally revolve around leaking information to anyone who can access the login form, the register form or the forgot password form. Basically, as it stands, PHPAuth will confirm if a specific email address has an account.

For example, when using a forgotten password form to request a new password a bad actor can put in any email address and if not valid, PHPAuth will return an error message telling the user that "Email address is incorrect". Whilst this is helpful for a genuine user, it also tells a bad actor that the email address entered does not have an account. Conversely, now that it is known that the system generates an error message when an invalid email is used a bad actor can identify genuine user accounts. This could lead to targeted 'spear phishing' attack on a specific user or set of users.

I know there is a lockout in place to prevent multiple reset attempts but this will only slow a bad actor down, not prevent them finding active accounts or using an already targeted list.

In this example, can PHPAuth be changed to send an email regardless? For example, if a bad actor enters target@target.domain then PHPAuth should show the message "Password reset request sent to email address." regardless if the email belongs to a registered user or not. The email that is sent should contain the password reset data if it is a valid account or should contain a message like "Someone attempted to reset a password for this email address but an account does not exist". This way, no user data is leaked from PHPAuth, a bad actor has no way of confirming valid accounts, anyone who is not registered becomes aware that someone is trying to use their email address for nefarious purposes and a user who is registered but is using the wrong email account will still know that it's the wrong one.

Is there any scope for this to be changed?

**Comment by Conver** [comment]
This is a good valid point and should be changed a long with a few other things, let's use the weekend to address all the privacy issues. Then on Monday when I'm home again I'll make a PR with the changed code.

**Comment by louis123562** [comment]
I do understand what you mean. But i got customers, which will call me, because the e-mail has not been send, but my Application (PHPAuth) said, there was. I guess we should add a parameter for this to the config, so everyone can decide on his own, which message comes back or how to handle "unknown mail addresses".

> For example, if a bad actor enters target@target.domain then PHPAuth should show the message "Password reset request sent to email address." regardless if the email belongs to a registered user or not.

I do not recommend to send a mail to an address, which is unknown to us. This could be used for SPAM-attacks. But as i mentiod before, we could add another paramater for the corresponding behaviour/situation, so that everyone can decide, what to do.

Please put in some more thoughts before we change the code.

**Comment by m0lmk** [comment]
Here's the ones I have found so far. Some just need the language file/SQL updating. I'm using the SQL translation table so can only comment on that.

Login
Email address with no user account produces an 'account_not_found' error (no database translation, maybe just missing from mine?). The error should be something like 'Email address / password are invalid.'

Register
Trying to register using an email address that is already registered produces an 'The email address is already in use.' error. Maybe this could be changed to produce an error again like 'Email address / password are invalid.' and send an email off to the registered user notifying them that someone has tried to create an account using their email. This would allow the user to know that they already have an account in then case of them forgetting or would let them know that a bad actor is attempting to use their email address.

Forgot Password
Already covered in my post above.

I understand @louis123562 comment about how sending email to unknown addresses could be used for SPAM attacks but the potential is very limited singe the content of the email can't be changed by a bad actor and the existing lockout feature will make it an extremely inefficient way to produce reset SPAM.

Adding a config option is a solution but allowing a bad actor to abuse the system to confirm live user accounts is not best practice for an auth system. Maybe a good compromise would be to allow a configurable setting but default to the most secure option?

Troy Hunt (a big player in web security) has an excellent resource on the subject for further reading... https://www.troyhunt.com/everything-you-ever-wanted-to-know/

**Comment by Conver** [comment]
status?
