### ISSUE TITLE
PHPAuth at Packagist

### ISSUE THREAD

**Issue by KarelWintersky** [PHPAuth/PHPAuth#398]
@liamjack , do you know, who is 'cuonic' ?

Maintaner of our project at packagist;

https://packagist.org/users/cuonic/ 
?

**Comment by Conver** [comment]
@KarelWintersky, @liamjack  is cuonic,.

Anything i can do for you?

**Comment by KarelWintersky** [comment]
yeah. deploy new release at packagist :)
or setup hooks for github on packagist :)

Better way is: register organisation email and transfer package ownership to it.

**Comment by Conver** [comment]
Okay, I'll try to remember reach him today, else I'll setup a new one.

**Comment by KarelWintersky** [comment]
@Conver , bump. I have a problems with update Packagist bundle

**Comment by Conver** [comment]
Sadly I don't use Packagist, so can't really this it and @liamjack doesn't respond to my mail. 

Lets set up a new one @KarelWintersky ?

**Comment by KarelWintersky** [comment]
we can't get onwership with https://packagist.org/packages/phpauth/phpauth 
owner is cuonic (@liamjack)

**Comment by liamjack** [comment]
Hey guys, sorry to keep you waiting, I've added @KarelWintersky as a maintainer for [phpauth/phpauth on Packagist.org](https://packagist.org/packages/phpauth/phpauth), @Conver if you create an account on Packagist.org I can add you aswell.

**Comment by liamjack** [comment]
Auto-update enabled, v1.1.4 is available via Composer

**Comment by louis123562** [comment]
Great :)

Holen Sie sich Outlook für Android<https://aka.ms/ghei36>

________________________________

**Comment by Conver** [comment]
@liamjack I have signed up now under same name as here.
