### ISSUE TITLE
reset and activation emails.

### ISSUE THREAD

**Issue by 8633brown** [PHPAuth/PHPAuth#399]
wondering if there is any reason the activation links don't include the activation key:

https://github.com/PHPAuth/PHPAuth/blob/752cda0ffe5742e06dce9242d0651b4cebf04db9/languages/en_GB.php#L63-L68
so:
`<a href="%1$s/%2$s">%1$s/%2$s</a>`
would become:
`<a href="%1$s/%2$s?code=%3$s">%1$s/%2$s</a>`
or something similar.

**Comment by louis123562** [comment]
Sounds good. In my application, after submitting mail for pw reset request, i directly show an input field for the key and the new passwort. I would also benefit from it :)

**Comment by Conver** [comment]
I'll make a PR for this today.

**Comment by Criptos** [comment]
I think this is solved  here: https://github.com/PHPAuth/PHPAuth/pull/445
