### ISSUE TITLE
config.php does not work on PostgreSQL

### ISSUE THREAD

**Issue by bplewe** [PHPAuth/PHPAuth#406]
Very happy with this package through 1.1.1, but I recently tried to upgrade it and it no longer works with PostgreSQL. In config.php, there are several "SHOW TABLES LIKE" queries added last year, but these are non-standard MySQL queries that don't work in PostgreSQL.

Fortunately, 1.1.1 is still working for me, but I'd like to be able to use the latest version.

**Comment by KarelWintersky** [comment]
is there any equivalent for 'show table like' in PgSQL?

**Comment by bplewe** [comment]
I think the nearest thing is:
SELECT table_name FROM information_schema.tables WHERE table_schema = 'public' AND table_name = 'config'

**Comment by fzmaster** [comment]
this component must control which database its connecting. Besides, on line 87 of Config.php, it could be replaced or added the following query:

> SELECT * FROM pg_catalog.pg_tables WHERE  tablename LIKE '{$this->config_table}'

**Comment by Conver** [comment]
I don't use PostgreSQL so I can't test it, so if someone can test and make a PR then I'll approve it.

**Comment by KarelWintersky** [comment]
fixed at https://github.com/PHPAuth/PHPAuth/commit/8675fbebf953a6b5046d9fb17986b8963c89ab82
