### ISSUE TITLE
Deprecated: On PHP7.4

### ISSUE THREAD

**Issue by txemaquintero** [PHPAuth/PHPAuth#407]
There is this Deprecated on PHP7.4:

Deprecated: Array and string offset access syntax with curly braces is deprecated in /Users/madtxema/BITBUCKET/webtecnet/oms/omsapp/vendor/phpauth/phpauth/Auth.php on line 1567

**Comment by KarelWintersky** [comment]
Fixed at eabcc66f5d39f9afd2d145654f7855e55b8ca792 , try again

**Comment by KarelWintersky** [comment]
@txemaquintero , I built new release - 1.1.14, but I have no control over Packagist account.
Update can be long...

Please, comment issue, not a code
