### ISSUE TITLE
Auth->CheckSession - comparing IP necessary? Reasons?

### ISSUE THREAD

**Issue by louis123562** [PHPAuth/PHPAuth#408]
Hey,

i am using PHPAuth to authenticate users who are using the browser and now also users with an Android and iOS App (ionic). Because of the changing IP-Adresses of the users on their mobiles (different WiFi's, mobile data) the authentication is invalid, until the IP addresses match (from where you logged in).

What i could do:
- Store the UID (Unique Device ID) in the sessions table and compare it instead of the IP
- put in a switch for mobile auth to pass the IP matching

I think the first approach would be fine. Any thoughts on this?

**Comment by turbopixel** [comment]
The comparison of the IP address is a useful security check. 

In theory:

1. Suppose I log on and I get a Cokkie with the PHPSESSID '35gqh9h8hth4vnq4r42r5b13gi'. In the browser I can read the cookie and copy the ID.

![grafik](https://user-images.githubusercontent.com/15839724/82804054-d8978580-9e81-11ea-8943-5b5d2be98688.png)

2. Now I change the device and create a PHPSESSID cookie with the same ID '35gqh9h8hth4vnq4r42r5b13gi'. 

3. And now I am logged in as the same user.

I have already tested it on the IT News page winfuture.de. (Log in, copy cookie and I am logged in on my second device as well)

-----
Nevertheless, I am with you. There should be an optional possibility to compare another data source (Device ID or so).

**Comment by louis123562** [comment]
Yeah, i meanwhile use the config attribute 'allow_concurrent_sessions' for multiple sessions for a user and i added a device_id column to my phpauth_session table for App-Sessions. The player_id is used for OneSignal push notifications.

<img width="1440" alt="grafik" src="https://user-images.githubusercontent.com/36068395/82809167-c28ec280-9e8b-11ea-88dc-34ef7e969262.png">

**Comment by louis123562** [comment]
I made a pull request for my implementation.
