### ISSUE TITLE
Creates a new record with null data if we send a field that doesnt exist

### ISSUE THREAD

**Issue by brunoMachado92** [PHPAuth/PHPAuth#409]
Hello,

wrongly, I set up the code to register a new user, like this:

$registerNow = $auth->register('fakemail@mail.pt', 'pwpwpw', 'pwpwpw',['name'=>'fakeUser']);

The field "name" does not exist on the user's table but the records get created anyway with empty data.
![image](https://user-images.githubusercontent.com/13498580/75099389-0b975800-55b9-11ea-9dd8-66b4f14b4bf7.png)

Php returns an error though.

**Comment by louis123562** [comment]
You could implement a validate-function for your parameters. We cannot handle wrongly set up tables / function calls.

**Comment by Conver** [comment]
You need to make sure you have the correct table, that's not something we can do.


However, it is meant to create a null record which will be filled when the user has activated.
