### ISSUE TITLE
Session Management

### ISSUE THREAD

**Issue by ejayfl** [PHPAuth/PHPAuth#420]
PHPAuth is awesome, but how do we extend the session system to save and retrieve data using PHP superglobal $_SESSION.

This is very important!!

**Comment by louis123562** [comment]
Why do you want to use PHP Sessions? As far as i know they are more insecure.

**Comment by Conver** [comment]
You mean you want to be able to retrieve session data thu Flight like `Flight::request()->session`

**Comment by ejayfl** [comment]
My app is built on PHPAuth, I need to pass CSRF token on the registration form. How do I achieve this? Another use case is the need to pass data between pages in a session.

**Comment by louis123562** [comment]
You can store data in a cookie (client) or on the Server. What data do you want to pass through your pages?

**Comment by ejayfl** [comment]
I intend to pass CSRF token from the client to the server. Can you show an example of this "You can store data in a cookie (client) or on the Server"

**Comment by louis123562** [comment]
Meh cant create nice links on mobile....

Create a cookie on Client which can be read by Server
https://www.php.net/manual/en/function.setcookie.php

**Comment by louis123562** [comment]
Otherwise use a database like mysql and store your data.
