### ISSUE TITLE
mysql defaults to latin1_swedish_ci collation

### ISSUE THREAD

**Issue by jmhumphrey** [PHPAuth/PHPAuth#422]
This is a nitpick really but most of the tables that are defined at "latin1" charsets will default to latin1_swedish_ci collation.  Probably because the mysql developer decided to use this default.  Like I said its a nitpick.    It would be nice if you would add the collate line to the table definition.

DEFAULT CHARACTER SET = latin1
COLLATE = latin1_general_ci;

I realize it has been added to specific columns in the definition but unless you specify it will default to Swedish.  Nothing against Swedes, just thought general would be more universal.

**Comment by KarelWintersky** [comment]
```
DROP TABLE IF EXISTS `phpauth_sessions`;
CREATE TABLE `phpauth_sessions` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `uid` int(11) NOT NULL,
  `hash` char(40) CHARACTER SET latin1 COLLATE latin1_general_ci NOT NULL,
  `expiredate` datetime NOT NULL,
  `ip` varchar(39) NOT NULL,
  `agent` varchar(200) NOT NULL,
  `cookie_crc` char(40) CHARACTER SET latin1 COLLATE latin1_general_ci NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
```
Enough?
