### ISSUE TITLE
examples

### ISSUE THREAD

**Issue by alph666** [PHPAuth/PHPAuth#424]
you need to create example files...

**Comment by KarelWintersky** [comment]
you need to read README.md

**Comment by KarelWintersky** [comment]
you need to read README.md

**Comment by KarelWintersky** [comment]
you need to read README.md

**Comment by KarelWintersky** [comment]
you need to read README.md

**Comment by KarelWintersky** [comment]
you need to read README.md

**Comment by KarelWintersky** [comment]
you need to read README.md

**Comment by KarelWintersky** [comment]
you need to read README.md
