### ISSUE TITLE
extending an existing session timestamp

### ISSUE THREAD

**Issue by louis123562** [PHPAuth/PHPAuth#426]
hey,

what do you think about extending an existing session, so the user stays logged in for another X days?

what is your opinion on this? how would you implement it?

**Comment by KarelWintersky** [comment]
`cookie_forget` : the time a user will remain logged in when not ticking "remember me" on login. Must respect PHP's strtotime format.

May be `+1 month`

**Comment by louis123562** [comment]
Mmh... i do know this config-param, but i mean it more like every time the user is "active", like open another secured page, the timestamp gets updated.

**Comment by KarelWintersky** [comment]
Fork, implement, PR :)

something like `renewUserSession()`

**Comment by Conver** [comment]
I've already made this function, I can push it later today

**Comment by louis123562** [comment]
yeah okay, all i wanted is just your opinion on this, if it is good practice an so on :)

**Comment by Conver** [comment]
added (https://github.com/PHPAuth/PHPAuth/commit/c0184c97332eb05eb885ec743444ab9b9b133d16)
