### ISSUE TITLE
german translation

### ISSUE THREAD

**Issue by louis123562** [PHPAuth/PHPAuth#428]
Hey,

there are some mistakes in the german translation, e. g.:

`$lang['email_reset_body'] = '..... folgenden Sicherheitsschlüssel: <strong>%3$s</strong><br/><br/>Wenn dein Passwort auf %1$s gar nicht zurücksetzen willst, dann ignoriere diese E-Mail bitte einfach.';`

`$lang['email_reset_body'] = '.....  folgenden Sicherheitsschlüssel: <strong>%3$s</strong><br/><br/>Wenn du dein Passwort auf %1$s gar nicht zurücksetzen willst, dann ignoriere diese E-Mail bitte einfach.';`

Also the speech? / salutation / form of address is in the 'you'-form instead of 'Sir/Mis' -> it is very casually and not professional.

If it is okay, i would transform the german strings into a more professional form and create a pull request.

Example (for our german people):

$lang['user_blocked'] = "Dein Benutzer ist im System aktuell gesperrt.";
becomes
$lang['user_blocked'] = "Ihr Benutzer ist im System gesperrt."; //'aktuell' is unecessary.

--------

$lang['logged_in'] = "Du bist jetzt angemeldet.";
becomes
$lang['logged_in'] = "Sie sind jetzt angemeldet.";

**Comment by KarelWintersky** [comment]
fork -> commit -> pull request ;-)
Welcome

**Comment by louis123562** [comment]
Thank you :)
