### ISSUE TITLE
Activation mail incomplete

### ISSUE THREAD

**Issue by iScripters** [PHPAuth/PHPAuth#43]
Had to switch back to commit 3d41c427de389aec37f073b63890cd1cf680053e to solve this issue. The activation mail gets cut off after "by clicking on the following link :" on any version after the above mentioned commit.

**Comment by mooztik** [comment]
oups sorry, it s me, i forgot a little string for each wildcard :dart: 
i ll pull a request with fixed text files now

**Comment by mooztik** [comment]
fixed, can be closed
