### ISSUE TITLE
Return key when not sending e-mail for password reset request

### ISSUE THREAD

**Issue by louis123562** [PHPAuth/PHPAuth#447]
**Is your feature request related to a problem? Please describe.**
Using the method requestReset($mail_address, $send_mail) allows to create a password-request for a given mail-address, but does not return the key when i dont want to send the mail via PHPAuth (but on my own).

The standard mail-template of PHPAuth is very 'slim' (only text) and for my (new) users this mail appears sometimes to be a phishing/spam mail.

**Describe the solution you'd like**
the method requestReset($mail_address, $send_mail) should at least return the key, if the second parameter is set to false. 

**Describe alternatives you've considered**
the method could also return every text-part of the email, so i can use them in my own template.
or there is a way of telling PHPAuth to use a given mail-template.

**Additional context**
<img width="1325" alt="grafik" src="https://user-images.githubusercontent.com/36068395/95075217-1cdc4180-0710-11eb-889d-cec553ffdaf8.png">

**Comment by turbopixel** [comment]
Since the last change, the method also returns always the key and the expiration date:

```php
        $state['error'] = false;
        $state['message'] = ($use_email_activation == true ? $this->__lang("reset_requested") : $this->__lang('reset_requested_emailmessage_suppressed'));
        $state['token'] = $addRequest['token'];
        $state['expire'] = $addRequest["expire"];

        return $state;
```
https://github.com/PHPAuth/PHPAuth/blob/master/Auth.php#L319

So if e-mail sending is disabled in the configuration, you can manually create an e-mail template.

**Comment by louis123562** [comment]
ah for sure - somehow i repressed this commit... upsi

**Comment by louis123562** [comment]
ah - i only looked into the wiki - it is not up to date with the current code. I will update it
