### ISSUE TITLE
Is it possible to add comments to the fields in the database file?

### ISSUE THREAD

**Issue by zhangchenglin** [PHPAuth/PHPAuth#454]
`
https://github.com/PHPAuth/PHPAuth/tree/master/database_defs
`
The sql file in the folder.

If you have time, can you add comment information for the fields in the database table?

`
D:\PhpstormProjects\GitHub\PHPAuth\languages\
`
In addition, the translated files can be provided directly and PR can be done? E.g:
zh_CN.php？

**Comment by zhangchenglin** [comment]
> if you want to contribute join our discord server: https://discord.gg/rGgEck

Must he be used? I don't seem to be so convenient, because of the network and language.

**Comment by louis123562** [comment]
No, you dont need to. Just make PR.

**Comment by zhangchenglin** [comment]
> No, you dont need to. Just make PR.

Can I resend an invitation? The previous one has failed.

**Comment by louis123562** [comment]
https://discord.gg/a5vuek

**Comment by Conver** [comment]
Do you want us to add comments to the SQL file explaining what the different configs are for?

**Comment by zhangchenglin** [comment]
> Do you want us to add comments to the SQL file explaining what the different configs are for?


Sorry, I didn't pay attention before, I have already explained it here.

https://github.com/PHPAuth/PHPAuth#configuration

**Comment by KarelWintersky** [comment]
Discord Invitation failed, @louis123562

**Comment by louis123562** [comment]
https://discord.gg/fh8G5j
