### ISSUE TITLE
Why is recaptcha_enabled directly assigned to true?

### ISSUE THREAD

**Issue by zhangchenglin** [PHPAuth/PHPAuth#459]
https://github.com/PHPAuth/PHPAuth/blob/70f684b3b59087b26ceab54f86c95e8193025084/Config.php#L211

https://github.com/PHPAuth/PHPAuth/blob/70f684b3b59087b26ceab54f86c95e8193025084/Config.php#L212-L213

Why is recaptcha_enabled directly assigned to true?

**Comment by Conver** [comment]
Not sure what you mean?

**Comment by zhangchenglin** [comment]
> Not sure what you mean?

https://github.com/PHPAuth/PHPAuth/blob/70f684b3b59087b26ceab54f86c95e8193025084/Config.php#L211

Why didn't he press the value in the database, but gave true directly.

**Comment by KarelWintersky** [comment]
Bug.

**Comment by KarelWintersky** [comment]
#464 fixes it

**Comment by KarelWintersky** [comment]
@Conver , Also, I lost ability to close issues. Why?

**Comment by Conver** [comment]
@KarelWintersky - I'm doing some changes to PHPAuth, getting it ready to be updated to PHPAuth v2, so I've changed a few permissions and such, I though you were done, since you are doing your own v2, but you are welcome to ping me on Discord, then we can discuss it.

**Comment by KarelWintersky** [comment]
I don't know your discord, @Conver
