### ISSUE TITLE
session and cookie duration

### ISSUE THREAD

**Issue by mooztik** [PHPAuth/PHPAuth#46]
is this a bug or not ?
```php
if($remember == true) {
			$data['expire'] = date("Y-m-d H:i:s", strtotime($this->config->cookie_remember));
			$data['expiretime'] = strtotime($data['expire']);
		} else {
			$data['expire'] = date("Y-m-d H:i:s", strtotime($this->config->cookie_remember)); <<-- B]
			$data['expiretime'] =0;   <<------A] value to zero,
		}
```
 A] the cookie duration is set to zero, then, if we use it as is, the cookie duration is set to nothing, created and deleted , the cookie nether be created

B] expire is set to cookie_remember duration for each of this option. if not remembered, this will be cookie_forget 

then the code need to be like this ?
```php
if($remember == true) {
			$data['expire'] = date("Y-m-d H:i:s", strtotime($this->config->cookie_remember));
			$data['expiretime'] = strtotime($data['expire']);
		} else {
			$data['expire'] = date("Y-m-d H:i:s", strtotime($this->config->cookie_forget)); 
			$data['expiretime'] = strtotime($data['expire']);
		}
```
it s more logical this way...

**Comment by cuonic** [comment]
Expire time is the value used as the expiry time in the session cookie, and to ensure that the cookie is removed at the end of the session (when the browser is closed) the expiry time should be set to 0, more info is available [here](http://php.net/manual/en/function.setcookie.php)
