### ISSUE TITLE
usage examples

### ISSUE THREAD

**Issue by DannyDrabkova** [PHPAuth/PHPAuth#480]
Hi there, it would be really nice to have some simple usage examples... simple log in ( nick + password ) exapmles ( php, not html)... or?

**Comment by louis123562** [comment]
Ahm - you will just need to call login($mail, $password).

But yeah, our goal in 2020 was to rewrite the docs....

**Comment by DannyDrabkova** [comment]
oh,  ... yes... I was too lazy thx :] :D
