### ISSUE TITLE
php8 support

### ISSUE THREAD

**Issue by kkretsch** [PHPAuth/PHPAuth#481]
**Describe the bug**
I seem to get some deprecated warning on Auth.php#660 for a functions parameter after an optional one.

As this makes upcoming header output unusable I had to disable deprecation warnings in php8, which isn't that helpful for a development instance.

    protected function addUser($email, $password, $params = [], &$use_email_activation)

**To Reproduce**
Use plain php8 docker instance which E_ALL default setting and try to create Auth object.

**Expected behavior**
I fear the syntax of that function has to be changed. All optional parameters to the end please.

**Comment by turbopixel** [comment]
I can confirm the message. I also had this.

**Comment by Conver** [comment]
The code hasn't been updated for v8 yet, but should be pretty easy to do tho.

**Comment by turbopixel** [comment]
I change the method parameters in the PR #482

**Comment by turbopixel** [comment]
@kkretsch Can you test the last changes? Should run on PHP 8 without any errors.

**Comment by kkretsch** [comment]
I tried the 1.2.1 version via composer under php 8.0.0 and it seems to work now. I see no errors anymore.
