### ISSUE TITLE
when $use_email_activation, "Undefined index: token"

### ISSUE THREAD

**Issue by totoprayogo1916** [PHPAuth/PHPAuth#483]
when set true at `$use_email_activation`
https://github.com/PHPAuth/PHPAuth/blob/ef48f584878fb5020545ab39cc9728961d93cabb/Auth.php#L188

row goes blank and "Undefined index: token"
https://github.com/PHPAuth/PHPAuth/blob/ef48f584878fb5020545ab39cc9728961d93cabb/Auth.php#L686

any extra setting for this?

**Comment by Conver** [comment]
What was the problem?

**Comment by totoprayogo1916** [comment]
> What was the problem?

forgot to set `emailmessage_suppress_activation`
now success,
but, no email delivered ...

**Comment by Conver** [comment]
Are you using sendmail or SMTP? ANd have you set it all up?

**Comment by totoprayogo1916** [comment]
Using SMTP
and this the config
```
smtp = 1
smtp_auth = 1
smtp_debug = 0
smtp_host = smtp.gmail.com
smtp_password = jwfemkkwkptpdmoi
smtp_port = 465
smtp_security = ssl
smtp_username = example@gmail.com
```

but no email sent

**Comment by Conver** [comment]
Have you tried enabling debug?

Also, I remember there is something about using Gmail SMTP, they limited that function, but cant remember how and why.

**Comment by totoprayogo1916** [comment]
debug was enable, but not work

but 

I have tried, the native sample of PHPMailer using Gmail SMTP like
https://github.com/PHPMailer/PHPMailer#a-simple-example
and its work

**Comment by totoprayogo1916** [comment]
working now,
after reading https://github.com/PHPAuth/PHPAuth/blob/ef48f584878fb5020545ab39cc9728961d93cabb/Auth.php#L921
before it was set to `1` and now I set it to `0`

thank you @Conver
