### ISSUE TITLE
Config.php __set method return type of "bool" throws an error with php 8.0.1, phpauth 1.3.0

### ISSUE THREAD

**Issue by smrose** [PHPAuth/PHPAuth#484]
With PHP 8.0.1 (but not PHP 7.4.14), Config.php doesn't compile because the return type specified for the __set() method, declared as "bool", so offends the compiler that it throws a fatal error with this message:

  PHP Fatal error:  PHPAuth\Config::__set(): Return type must be void when declared in /home/rose/public_html/phpauth/vendor/phpauth/phpauth/Config.php on line 253

To reproduce this error:

 php vendor/phpauth/phpauth/Config.php

That stops the show. Removing the return type fixes it, and returning a value from the function doesn't cause an error or warning.

The PHP I'm using is the one in the "remi" repository for Fedora Linux 33.

(I'm new at this. If my issue report could have been formulated more usefully, I'm all ears.)

**Comment by louis123562** [comment]
should be fixed now. feel free to continue testing :)
