### ISSUE TITLE
getRandomKey Why does this dictionary add numbers repeatedly and regularly?

### ISSUE THREAD

**Issue by ZhangChengLin** [PHPAuth/PHPAuth#487]
https://github.com/PHPAuth/PHPAuth/blob/f56159772525de39295cd44e018852d6150284c9/Auth.php#L1584-L1595

Why does this dictionary add numbers repeatedly and regularly?

**Comment by KarelWintersky** [comment]
Your offer?

**Comment by zhangchenglin** [comment]
> Your offer?

`
     $dictionary = "A1B2C3D4E5F6G7H8I9J0K1L2M3N4O5P6Q7R8S9T0U1V2W3X4Y5Z6a1b2c3d4e5f6g7h8i9j0k1l2m3n4o5p6q7r8s9t0u1v2w3x4y5z6"; 
`

Why not the continuous writing, but the interspersed writing.

`
$dictionary = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz1234567890";
`

**Comment by zhangchenglin** [comment]
> Your offer?

Questionning only, no opinion.

**Comment by KarelWintersky** [comment]
Not a bug
