### ISSUE TITLE
Undefined property: stdClass::$recaptcha 

### ISSUE THREAD

**Issue by totoprayogo1916** [PHPAuth/PHPAuth#489]
at this line, 
https://github.com/PHPAuth/PHPAuth/blob/fc1d176b26a5ac4e9f1c89a282632fdee7c65b98/Auth.php#L74-L75

`Undefined property: stdClass::$recaptcha `

`Undefined property: stdClass::$dictionary`

**Comment by zhangchenglin** [comment]
https://github.com/PHPAuth/PHPAuth/blob/master/Auth.php#L72

https://github.com/PHPAuth/PHPAuth/blob/master/Config.php#L61

https://github.com/PHPAuth/PHPAuth/blob/master/Config.php#L93
