### ISSUE TITLE
Not able to register user

### ISSUE THREAD

**Issue by SANCLA** [PHPAuth/PHPAuth#496]
Hey guys,

I'm a bit 'fresh' behind the ears when it comes to this framework and PHP in general.
I think i'm making an error somewhere but cant figure it out.

I replaced the sql connection parameters in this post to keep them safe.
Datebase connection is up and running, I am able to authenticate (and bounces because there are no users present).

When running the code below, I get zero response.
No message or array in $auth_result.
No feedback, no error message.

I'm missing something here...
Can you take a quick look and point me in the right direction?

I'm using a hosted environment from a third party hosting company.

Thanks!

```
<?php
include("Config.php");
include("Auth.php");

$dbh = new PDO("mysql:host=localhost;dbname=xxx", "xxx", "xxx");
$config = new PHPAuth\Config($dbh);
$auth   = new PHPAuth\Auth($dbh, $config);

    if ($_SERVER['REQUEST_METHOD'] == 'POST') {
		echo "Received post<br>";

		$post_email = $_POST["input_email"];
		$post_pass = $_POST['input_password'];
		$auth_result = $auth->register($post_email, $post_pass, $post_pass);
                print_r ($auth_result);	
...
```

**Comment by SANCLA** [comment]
Edit
I do get a response if the password do not match.
But, when the e-mail address is valid, and the passwords match, I do not get any response :-/

**Comment by SANCLA** [comment]
Trying to figure this out.
Could this related to dependencies, that are mentioned in the auth.php script?
And that are perhaps not present due to the fact that I used a hosted environment?

`
use ZxcvbnPhp\Zxcvbn;
use PHPMailer\PHPMailer\PHPMailer;
use ReCaptcha\ReCaptcha;`

**Comment by Conver** [comment]
Hey, I'll try to help you.

Do you have Discord? We have a server on there for easier support.

**Comment by SANCLA** [comment]
Nope, but I can set it up...

**Comment by Conver** [comment]
It will be easier, but we can do it here too :)

So, the register function doesn't return any data if register is successful, is that correct?
- If so, check if auto increment is activated for the ID field in the user table.

Have you tried activating PHP error function?

**Comment by SANCLA** [comment]
My Discord handle is SANCLA
So far, auto_increment has been enabled in the SQL database.
I used the query that was included with the release 1.2.1 to generate the tables.

Activating PHP error function is a good tip!

**Comment by SANCLA** [comment]
PHP error function enabled:
Fatal error: Namespace declaration statement has to be the very first statement or after any declare call in the script in /home/sancla20201105/domains/sense4air.com/public_html/control/Auth.php on line 21

That would be the **class Auth/* implements AuthInterface*/** line:

```
namespace PHPAuth;

use Exception;
use PDO;
use PDOException;
use RuntimeException;
use ZxcvbnPhp\Zxcvbn;
use PHPMailer\PHPMailer\PHPMailer;
use ReCaptcha\ReCaptcha;

/*require_once 'AuthInterface.php';*/

/**
 * Auth class
 * Required PHP 5.6 and above.
 *
 */
class Auth/* implements AuthInterface*/
{
    const HASH_LENGTH = 40;
    const TOKEN_LENGTH = 20;
```

**Comment by SANCLA** [comment]
Correction......
The previous error was one of my own cock-ups....
Fat finger syndrome finding bugs...

PHP error:
Notice: Undefined variable: loginerror in /home/sancla20201105/domains/xxx.com/public_html/control/registerpage.php on line 59
E-mail

**Comment by Conver** [comment]
What is expected to be in the loginerror var?

**Comment by SANCLA** [comment]
Yeah, that was an undeclared variable....
Getting there...
So eventually, after straightening everything out again, I got to this error:

Fatal error: Uncaught Error: Class 'ZxcvbnPhp\Zxcvbn' not found in /home/sancla20201105/domains/xxx.com/public_html/control/Auth.php:227 Stack trace: #0 /home/sancla20201105/domains/xxx.com/public_html/control/register.php(29): PHPAuth\Auth->register('test@test.com', 'Letstrythispassword666!', 'Letstrythispassword666!') #1 {main} thrown in /home/sancla20201105/domains/xxx.com/public_html/control/Auth.php on line 227

**Comment by Conver** [comment]
Did you install this by composer or manually?

**Comment by SANCLA** [comment]
Manually, upload to directory.
third party hosting plan...
Discord: SANCLA#4166

**Comment by Conver** [comment]
Contacting you on Discord in a few minutes

**Comment by SANCLA** [comment]
Ok, so after been in contact with Conver, here is the solution.
I only focussed on the ZxcvbnPhp class, skipping the PHPMailer and ReCaptcha class for now (I dont use it anyway).

1. Download the class manually from https://github.com/bjeavons/zxcvbn-php
2. Created a new folder path, in my case I used "classes/ZxcvbnPhp/"
3. Dump the files  from the src folder into this folder. (Zxcvbn.php, Matcher.php, subfolder Matchers, etc.
Basically, all these files: https://github.com/bjeavons/zxcvbn-php/tree/master/src
3. Edit the Auth.php file, so the beginning looks like this (IN THAT ORDER!):

```
namespace PHPAuth;

include("classes/ZxcvbnPhp/Matcher.php");
include("classes/ZxcvbnPhp/Scorer.php");
include("classes/ZxcvbnPhp/TimeEstimator.php");
include("classes/ZxcvbnPhp/Feedback.php");
include("classes/ZxcvbnPhp/Matchers/MatchInterface.php");
include("classes/ZxcvbnPhp/Matchers/BaseMatch.php");
include("classes/ZxcvbnPhp/Matchers/DictionaryMatch.php");
include("classes/ZxcvbnPhp/Matchers/ReverseDictionaryMatch.php");
include("classes/ZxcvbnPhp/Matchers/L33tMatch.php");
include("classes/ZxcvbnPhp/Matchers/RepeatMatch.php");
include("classes/ZxcvbnPhp/Matchers/SequenceMatch.php");
include("classes/ZxcvbnPhp/Matchers/SpatialMatch.php");
include("classes/ZxcvbnPhp/Matchers/YearMatch.php");
include("classes/ZxcvbnPhp/Matchers/Bruteforce.php");
include("classes/ZxcvbnPhp/Matchers/DateMatch.php");
include("classes/ZxcvbnPhp/Zxcvbn.php");

use Exception;
use PDO;
use PDOException;
use RuntimeException;
use ZxcvbnPhp\Zxcvbn;
use PHPMailer\PHPMailer;
use ReCaptcha\ReCaptcha;

...
```
