### ISSUE TITLE
Importing database_emails_banned.sql fails

### ISSUE THREAD

**Issue by AntonUden** [PHPAuth/PHPAuth#501]
seems like there are some duplicate entries up to line 105 where there is also an error

**Comment by KarelWintersky** [comment]
Looks like banned email list must be removed from PHPAuth Core to Plugin :)

**Comment by Conver** [comment]
I agree with @KarelWintersky

**Comment by KarelWintersky** [comment]
Now recommended using https://github.com/PHPAuth/PHPAuth.EMailValidator
