### ISSUE TITLE
Forgot Password

### ISSUE THREAD

**Issue by frankycalo** [PHPAuth/PHPAuth#502]
Hi,
is it possible to implement the forgot password functionality?
Thanks for the attention.

**Comment by louis123562** [comment]
hey,

we have this functionality.
See requestReset() method: https://github.com/PHPAuth/PHPAuth/blob/8684e965e7c66d7d69354f6b444ddef7bcb80a3a/Auth.php#L331

**Comment by frankycalo** [comment]
sorry, you're right I had nothing but password for.
Thanks for the clarification.
good job.  :-)

**Comment by louis123562** [comment]
no problem - you are very welcome.
you can join our discord if you have more questions: https://discord.gg/VkgXShga

**Comment by totoprayogo1916** [comment]
why not activate Github Discussion @louis123562 ?

**Comment by Conver** [comment]
@totoprayogo1916 done ;)

**Comment by louis123562** [comment]
Did not know that there is a discussion area here in github :)

Can i close this issue @totoprayogo1916 ?

**Comment by totoprayogo1916** [comment]
of course
close it @louis123562
