### ISSUE TITLE
Cookie is not cleared on logout

### ISSUE THREAD

**Issue by joeybab3** [PHPAuth/PHPAuth#507]
**Describe the bug**
When logging the user out, the cookie is not cleared. The session is deleted from the database but the cookie is not cleared from the browser which leads to it not being set when login() is called.

**To Reproduce**
1. Logout
2. Go to login page
3. Cookie is still present

**Expected behavior**
The cookie should be cleared

**Comment by livetradecom** [comment]
Hi,
is this already fixed? I am hesitant to use it if it hasn't been fixed yet.

**Comment by turbopixel** [comment]
Yes it's fixed (https://github.com/PHPAuth/PHPAuth/blob/b1a078443a3f315a397752476a647cf59fb05f13/Auth.php#L544)
