### ISSUE TITLE
Group of users + 3rd party signup/login ( fb,twitter,google+ ) - suggestion

### ISSUE THREAD

**Issue by imransilvake** [PHPAuth/PHPAuth#51]
Very awesome class. clean code. if "Group of users (admin, other users(subscriber etc))(especially) + 3rd party signup/login ( fb,twitter,google+ )" these can be implemented in these, it would be an ideal class for everyone. thanks alot for the code.

**Comment by imransilvake** [comment]
issue:
 Notice: Undefined variable: s in ..\languages\en.php on line 61
fixed by:
replacing %1$s by %1\$s - (adding slash as double quotes are being used.)

**Comment by cuonic** [comment]
Group support has already been request with issue #24, 3rd party authentication is more advanced and is covered by more advanced classes like [Opauth](http://opauth.org), it is not something that will be implemented in PHPAuth, the idea is to keep things simple.
