### ISSUE TITLE
Localhost error 500 after installing PHPAuth

### ISSUE THREAD

**Issue by vanauss** [PHPAuth/PHPAuth#515]
Hi, 
i coding my little project and after install with composer my localhost folder return 500 error.Same after remove via composer and delete config file. Others folders on localhost run as charm. Tried to google, nothing found. Any ideas whats going on ? I run on linux Mint

many thanks,
Van

**Comment by KarelWintersky** [comment]
```
tail /var/log/nginx/.... .log
or 
/var/log/apache2/...log
tail /var/log/php*.log
```
See your log files. All anwers is there
