### ISSUE TITLE
usage examples?

### ISSUE THREAD

**Issue by lospo** [PHPAuth/PHPAuth#52]
Hi, and good morning.
Is there any example of all the feature of this class?
I see only "how to secure a page"

THANKS

**Comment by Yadziro** [comment]
Hello! I subscribe to the author above. It would be interesting to look at the examples of use.

**Comment by alteredorange** [comment]
Yes, an simple login example would be great!  I was able to secure a page, but have no idea how to let users register and sign in :/

**Comment by cuonic** [comment]
I thought this would be pretty obvious, it's the second method in the class:

`public function login($email, $password, $remember = 0)`

So to log a user in via a form:

```
<?php

include("languages/en.php");
include("config.class.php");
include("auth.class.php");

$dbh = new PDO("mysql:host=localhost;dbname=phpauth", "username", "password");

$config = new Config($dbh);
$auth = new Auth($dbh, $config, $lang);

$login = $auth->login($_POST['username'], $_POST['password'], $_POST['rememberme']);

if($login['error']) {
    // Something went wrong, display error message
    echo '<div class="error">' . $login['message'] . '</div>';
} else {
    // Logged in successfully, set cookie, display success message
   setcookie($config->cookie_name, $login['hash'], $login['expire'], $config->cookie_path, $config->cookie_domain, $config->cookie_secure, $config->cookie_http);
    echo '<div class="success">' . $login['message'] . '</div>';
}

?>
```

**Comment by soldiertt** [comment]
Thank you for the example, also when authenticated how can we retrieve the user email ? I need at least to have access to the user profile (email, id, ..)

**Comment by cuonic** [comment]
Take a look at the following items of the Documentation:

* https://github.com/PHPAuth/PHPAuth/wiki/Class-Methods#getsessionuid
* https://github.com/PHPAuth/PHPAuth/wiki/Class-Methods#getuser

**Comment by 1quest** [comment]
Just saying, it takes a looong time to find out the format of the cookie. Or I was just dropped one time too many as a child.

Loving the whole thing tho, you guys are uhmazing!
