### ISSUE TITLE
getIP() brute-force protection can be bypassed. getenv('REMOTE_ADDR') should be used before other headers.

### ISSUE THREAD

**Issue by jcsuen** [PHPAuth/PHPAuth#528]
IP Based Brute-force protection can be easily bypassed

By adding the header X-Forwarded-For with the value of an IP address that changes with each request, an attacker is able to carry out a brute-force attack against the login form / system.

Example request:
_POST /login.php HTTP/1.1
Host: <-redacted>
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:105.0) Gecko/20100101 Firefox/105.0
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,*/*;q=0.8
Accept-Language: en-GB,en;q=0.5
Accept-Encoding: gzip, deflate
Content-Type: application/x-www-form-urlencoded
Content-Length: 73
Origin: <-redacted>
Referer: <-redacted>
Upgrade-Insecure-Requests: 1
Sec-Fetch-Dest: document
Sec-Fetch-Mode: navigate
Sec-Fetch-Site: same-origin
Sec-Fetch-User: ?1
**X-Forwarded-For: 127.0.0.1**
The: trailers
Connection: close_

username=<-redacted>&password=<-redacted>

**Fix :** 
```
/**
     * Returns IP address of client ` 
     *
     * @return string $ip
     */

public static function getIp():string
    {
        # check REMOTE_ADDR first, as it cannot be easily spoofed like the following headers 
        if (getenv('REMOTE_ADDR')) { 
          $ipAddress = getenv('REMOTE_ADDR');  
        } elseif (getenv('HTTP_CLIENT_IP')) {
            $ipAddress = getenv('HTTP_CLIENT_IP');
        } elseif (getenv('HTTP_X_FORWARDED_FOR')) {
            $ipAddress = getenv('HTTP_X_FORWARDED_FOR');
        } elseif (getenv('HTTP_X_FORWARDED')) {
            $ipAddress = getenv('HTTP_X_FORWARDED');
        } elseif (getenv('HTTP_FORWARDED_FOR')) {
            $ipAddress = getenv('HTTP_FORWARDED_FOR');
        } elseif (getenv('HTTP_FORWARDED')) {
            $ipAddress = getenv('HTTP_FORWARDED');
        } else {
            $ipAddress = '127.0.0.1';
        }

        $ipAddress = explode(',', $ipAddress)[0];

        return $ipAddress;
    }
```

**Comment by KarelWintersky** [comment]
accepted
