### ISSUE TITLE
 MySQL Support 

### ISSUE THREAD

**Issue by phithi92** [PHPAuth/PHPAuth#531]
Hey,
in your description you refer your product with mysql support. I report the MySQL Bug #518 for more than a year. The complete functionality not working correct with MySQL. Its planed to fix this or do you still not more support MySQL? Would be nice to know

**Comment by JapCLoN** [comment]
Hello,

I will look into this today

**Comment by phithi92** [comment]
i would help, but last commit was rejected.

**Comment by JapCLoN** [comment]
Can you link me to that PR? can't seem to find it and i'll look into it.

**Comment by phithi92** [comment]
PR?

**Comment by JapCLoN** [comment]
Sorry, might be me misunderstanding you, though you meant the PR with your rejected commit.

**Comment by KarelWintersky** [comment]
https://github.com/PHPAuth/PHPAuth/pull/521

**Comment by JapCLoN** [comment]
@KarelWintersky, any reason why we didn't accept it?

**Comment by KarelWintersky** [comment]
@JapCLoN, 

> PDOStatement::execute returns true on success or false on failure.
> Failure is NOT a zero count. So, this command ALWAYS return TRUE.
> If sessions table is empty - next line throws NOTICE: index 'uid' not found and returns 0.
> Also, method must return int value, not boolean.

**Comment by JapCLoN** [comment]
ah okay @KarelWintersky, makes sense.

It should be possible to add a check on the fetch command if I remember correctly

**Comment by KarelWintersky** [comment]
I can't understand: is a error still present? 

@phithi92  ?

**Comment by phithi92** [comment]
@KarelWintersky yes in these 2 functions

https://github.com/PHPAuth/PHPAuth/blob/master/sources/Auth.php#L518
https://github.com/PHPAuth/PHPAuth/blob/master/sources/Auth.php#L567
