### ISSUE TITLE
Double Quotes Cause Error in en.php

### ISSUE THREAD

**Issue by adamcbuckley** [PHPAuth/PHPAuth#54]
Line 61 of `en.php` specifies a string into which values will be substituted using sprintf.

For me, the use of double quotes causes PHP to substitute `$s` before sprintf is able to parse the string for it's own substitution.

In my PHP log file I see the following errors:

```
PHP Notice:  Undefined variable: s in PHPAuth\languages\en.php on line 61
...
PHP Warning:  sprintf(): Too few arguments in PHPAuth\auth.class.php on line 670
```

I was able to fix the problem by adding a backslash before any dollar symbol.

Before: `<a href=\"%1$s/%2$s\">%1$s/%2$s</a>`
After: `<a href=\"%1\$s/%2\$s\">%1\$s/%2\$s</a>`

I am using PHP version 5.4.24 on 32-bit Windows 7.

Cheers, Adam.

**Comment by cuonic** [comment]
How about using single quotes ?

**Comment by livmackintosh** [comment]
Hi Adam,

I have the same problem and your fix works really well, thank you :) :+1: 

Liv
