### ISSUE TITLE
validateEmail() returning false positives

### ISSUE THREAD

**Issue by human-inhabitant** [PHPAuth/PHPAuth#55]
My Environment:
```
System          : Windows Server 2012 R2 Datacenter Edition i586
Server Software : Microsoft-IIS/8.5
Server API      : CGI/FastCGI
PHP Version     : 5.6.8
```

When ```validateEmail( $email )``` is testing against the ```json_decode( domains.json )``` it compares using ```in_array()``` utilizing the entire passed email address:

Theoretic example:
```
in_array( strtolower( $email ), $bannedEmails );
     --- or ---
in_array( strtolower( 'human@ag.us.to' ), 'ag.us.to' );
```

The former is failing, for me, but the following fix seems to be working okay.

```
in_array( strtolower( explode( '@', $email )[1] ), $bannedEmails );
     --- or ---
in_array( strtolower( 'ag.us.to' ), 'ag.us.to' );
```

The email address is well validated to this point within the method, so the inline ```explode``` did not seem too intrusive. Strict option on ```in_array``` added no value as it is just a __*type*__ thing anyway.

**Comment by cuonic** [comment]
Thanks for spotting that ! Fixed with commit 3d199463f684ee8ccbf48cbc6ea7181212622df0
