### ISSUE TITLE
Password is too short no matter the length.

### ISSUE THREAD

**Issue by guyoverhere** [PHPAuth/PHPAuth#56]
No matter the length of password I use I get the Password is too short error returned. The following is the code I am using:

```
<?php
require (dirname(dirname(__FILE__)) . '/includes/resources/languages/en.php');
require (dirname(dirname(__FILE__)) . '/includes/resources/config.class.php');
require (dirname(dirname(__FILE__)) . '/includes/resources/auth.class.php');
require (dirname(dirname(__FILE__)) . '/includes/configure.php');
$config = new Config($dbh);
$auth = new Auth($dbh, $config, $lang);
$register = $auth->register($_POST['email'], $_POST['username'], $_POST['password'], $_POST['repeatpassword']);
if($register['error']) {
    // Display error message
    echo '<div class="error">' . $register['message'] . '</div>';
} else {
 // Registered successfully
 echo '<div class="success">' . $register['message'] . '</div>';
}
  ?>
```
Keep in mind that I'm using configure.php to hold the db connection stuff so I don't have to do `$dbh = new PDO("mysql:host=localhost;dbname=phpauth", "username", "password");`

My markup page is just as follows:
```
  <form name='register' action='registertest.php' method='POST' />
<label for 'email'></label><input type="text" name="email" placeholder="Email" />
<label for 'username'></label><input type="text" name="username" placeholder="Username" />
  <label for 'password'></label><input type="password" name="password"  placeholder="password" />
    <label for 'repeatpassword'></label><input type="password" name="repeatpassword"  placeholder="repeat password" />
<label for 'Submit'></label><input type="submit" name="Submit" id="login" value="Submit" />
```

**Comment by cuonic** [comment]
There is no username in the current version. Take a look at the [code](https://github.com/PHPAuth/PHPAuth/blob/master/auth.class.php#L116) and the [wiki](https://github.com/PHPAuth/PHPAuth/wiki/Class-Methods#register)

**Comment by guyoverhere** [comment]
Ha! Guess I should have looked at that part of the code, I was basing my code off of the old version but it works now. I am wondering why there is no salt stored in the database however.

**Comment by Conver** [comment]
@guyoverhere there is no salt stored because the salt is included in the password hash.

http://php.net/manual/en/faq.passwords.php#faq.password.storing-salts

**Comment by guyoverhere** [comment]
Thanks for the info. Everything is working perfectly now.
