### ISSUE TITLE
Undefined index: key_invalid

### ISSUE THREAD

**Issue by human-inhabitant** [PHPAuth/PHPAuth#57]
My Environment:
```
System          : Windows Server 2012 R2 Datacenter Edition i586
Server Software : Microsoft-IIS/8.5
Server API      : CGI/FastCGI
PHP Version     : 5.6.8
```

When the method ```activate()``` is testing length ```( strlen( $key ) !== 20 )```, if ```true``` it returns the message ```$lang['key_invalid']``` but that index does not exist *(I checked both en.php and fr.php)*.

In most cases, when dealing with ```key_invalid``` anyway,  a string is appended to the index; ```activation``` or ```reset``` just not in this case. There are no other relevant __*key*__ length messages that I could find in the language files.

So, for my usage, I just swapped ```key_invalid``` for ```activationkey_incorrect```, seems to work for both *too long* and *too short* items,....

```php
if ( strlen( $key ) !== 20 ) {
  . . .
  $return['message'] = $this->lang['key_incorrect'];

     //--- to ---

if ( strlen( $key ) !== 20 ) {
  . . .
  $return['message'] = $this->lang['activationkey_incorrect'];
```

There is the same sort of thing going on within ```resetPass()``` when testing ```( strlen( $key ) != 20 )```.

I swapped out the same indexes for the ```$lang``` array but used ```resetkey_incorrect``` instead and updated the test to a *not identical ( !== )* to match the test given in ```activate()```.

```php
if ( strlen( $key ) != 20 ) {
  $return['message'] = $this->lang['key_invalid'];

     //--- to ---

if ( strlen( $key ) !== 20 ) {
  $return['message'] = $this->lang['resetkey_incorrect'];
```

__Update:__
I found one additional missing index ```account_deleted``` within ```deleteUser()```, for my usage I had to add it within the ```$lang``` array.

**Comment by cuonic** [comment]
Thanks again for that, fixed with commits c9038c821d52fad86cd80c2c2f8923033a8520b6 and ede27c50ca2db4cfdab0ea163435b19d70cecffe
