### ISSUE TITLE
Suggestion: Remove column 'salt' from database.sql if it's redundant.

### ISSUE THREAD

**Issue by livmackintosh** [PHPAuth/PHPAuth#59]
# NULL Salt without throwing error

After invoking *register()* and activating, login() throws "Email address / password are invalid." error because the Salt is *NULL*.

Maybe mcrypt can't read /dev/urandom, could be a local permissions problem but would help to check if Salt is *NULL* with a conditional statement before passing to database?

**Comment by livmackintosh** [comment]
Update: Duplicate issue, closed and now fixed.

**Comment by livmackintosh** [comment]
Suggestion: Remove column 'salt' from database.sql if it's redundant?

**Comment by cuonic** [comment]
It is indeed redundant, I removed it on my sites but not on here ! Thanks for spotting. Fixed with commit d5f33ed2eab1cb042b8205782c647beba4dfd43e
