### ISSUE TITLE
PHPAuth 2 - Spring cleaning for a fresh start

### ISSUE THREAD

**Issue by cuonic** [PHPAuth/PHPAuth#6]
Hi,

I would like the PHPAuth project to kick off again to provide web developers an easy way of integrating basic user authentication into their website, so recently I spent some time working on sorting out the code.

I've just finished ironing out some of the last errors from PHPAuth, some of the stuff I've done :
- A remember me parameter on login
- Bcrypt hashing via password_hash for increased security
- Password verification with password_verify
- Removed useless functions, configuration parameters and variables
- Remove OTP, languages and groups until we can do this in a clean manner, which I plan to develop shortly.

Using password_* functions means that the PHPAuth class will now require PHP 5.5+ to operate correctly. There is a compatibility class available, but I feel that it will just make more of a mess, and maybe this will encourage users to update their installations where possible to the latest PHP version. That's my opinion anyway.

That's why I'm writing here, because I want your opinion and I also need to know that the PHPAuth class works 100% in a test environment, so I set up a quick demo :

[http://lab.cuonic.com/](http://lab.cuonic.com/)

I need you to use all the different functions (register, activate, login, logout, change password, change email, forget password, resend activation email) in both normal contexts (with the correct information) but also in abnormal contexts (put the wrong password in willingly), until you get an error, be it a "System error" response or no response at all, I need to know how you created that error, so that it can be fixed.

Here is the current source code I'm using for the Auth class on the demo site (including database and config file) so you can also inspect the code before pushing it properly : [http://ovh.to/xu4eABA](http://ovh.to/xu4eABA)

Any comments, suggestions, or issues are welcome, thanks for helping out :)

**Comment by ikennah** [comment]
Happy 2015, is this still an active project?

**Comment by Conver** [comment]
Happy 2015 ikennah, yes.. it is still active
