### ISSUE TITLE
restricted page example

### ISSUE THREAD

**Issue by aldisseia** [PHPAuth/PHPAuth#63]
an example of how I do to protect the restricted page?
html5 "json" -> PHPAuth
PHPAuth "json (Token)" -> html5

**Comment by cuonic** [comment]
How to restrict access to a page (in README.md): https://github.com/PHPAuth/PHPAuth#how-to-secure-a-page

I don't understand what you are trying to explain after the first line.

**Comment by aldisseia** [comment]
I have an application in Phonegap (HTML5), and need to authenticate with the token, how can I do this:
html5 "json" -> PHPAuth
PHPAuth "json (Token)" -> html5

**Comment by cuonic** [comment]
I have never used Phonegap so I can't really help you here.

**Comment by aldisseia** [comment]
I believe you do not understand ...
An application in html + jquery emcaminha login and password for the application server, only for this to work the routes served should a token in the HTTP header and when this html + jquery application wants to give an insert the server must verify that the token is same as forwards via header ...

**Comment by cuonic** [comment]
I'm sorry I don't understand

**Comment by Conver** [comment]
@aldisseia The token you are talking about, what token is that?

I think I may understand what you mean, and I think I have a solution for you.

It's not a normal way to do it, but if you prefer using PHPAuth, then its possible, but you should look for something in the language you use.

let me know.
