### ISSUE TITLE
Naming scheme of languages

### ISSUE THREAD

**Issue by sr-verde** [PHPAuth/PHPAuth#65]
I would suggest a naming scheme for languages like de_DE or en_US. That would allow different language files for different countries but same language. :)

**Comment by Conver** [comment]
Not totally following you..

You mean, that if we use that kind of scheme, then it can automatically be detected with language to use?

**Comment by sr-verde** [comment]
No, I mean you can differ between e.g. British English (en_GB) and American Englisch (en_US).

**Comment by cuonic** [comment]
Good idea, implemented with commit 110d36ccdb8865c4a250622d7a00e8a213d7b048

**Comment by sr-verde** [comment]
Great. :+1:
