### ISSUE TITLE
Missing entry in the $lang array (referenced by resetPass method)

### ISSUE THREAD

**Issue by extendmarketing** [PHPAuth/PHPAuth#66]
The following entry, referenced by the `resetPass` method in the `Auth` class seems to be missing from the `$lang` array: 

`$lang['newpassword_match']`

**Comment by Conver** [comment]
Which language file are you using?

**Comment by cuonic** [comment]
Duplicate of #58, which was fixed with commit 926775b. Try updating to the latest version ?
