### ISSUE TITLE
SMTP Error when creating a user

### ISSUE THREAD

**Issue by zachyarid** [PHPAuth/PHPAuth#67]
I have my SMTP settings in the DB but for some reason, whenever I try to create a new account, it kicks back with error #10. I'm not sure what is causing this problem as I know that my SMTP settings are correct. 
Below are the settings in the DB
![screen shot 2015-08-27 at 4 31 10 pm](https://cloud.githubusercontent.com/assets/11239441/9559294/a376ff1e-4db6-11e5-9bd4-ed50cf6bffc8.png)

I've tried putting smtp_auth = 1 (also the port and security to the proper values) but I am still getting the same error message.

Any idea as to what my issue might be?

**Comment by Conver** [comment]
Not sure which error you are getting?

**Comment by zachyarid** [comment]
It's this one: Failed to send activation / reset email (Sendmail / SMTP problem)

**Comment by zachyarid** [comment]
Are there any gotcha's when configuring the SMTP server settings in the database?

**Comment by Conver** [comment]
Would you be able to point me to some of the lines with gives you the error, and which method you are using.

I think I might have found the problem, we are currently not checking if SMTP auth is null, so its getting some wrong information. 

I'll wait for your response before further testing.

**Comment by zachyarid** [comment]
```
include("languages/en.php");
include("config.class.php");
include("auth.class.php");
	
$dbh = new PDO("mysql:host=localhost;dbname=*omit*", "*omit*", "*omit*");
	
$config = new Config($dbh);
$auth = new Auth($dbh, $config, $lang);
	
$return = $auth->register($_POST['email'], $_POST['password'], $_POST['repeatpassword']);
	
if($return['error']) {
echo '<div style="color:red;"class="error">' . $return['message'] . '</div>';
exit();
}
setcookie($config->cookie_name, $return['hash'], $return['expire'], $config->cookie_path, $config->cookie_domain, $config->cookie_secure, $config->cookie_http);
echo '<div class="success">' . $return['message'] . '</div>';
```

Here's the PHP code that I have at the top of the page.

**Comment by Conver** [comment]
And you are getting this error? "Failed to send activation / reset email (Sendmail / SMTP problem)"

The problem is that that error string is not located in the lang file, so I'm not sure which line is giving you the error.

You are sure that your $_POST does contain data?

**Comment by zachyarid** [comment]
Correct, error number 10.

I am sure that POST contains data. Just checked it

**Comment by Conver** [comment]
I'm unable to check right now.

but I think I found the problem, you need to add a NULL checker for "$this->config->smtp_auth". Like

if(!is_null($this->config->smtp_auth)) {
$mail->Username = $this->config->smtp_username;
$mail->Password = $this->config->smtp_password;
}
$mail->SMTPAuth = $this->config->smtp_auth;

Around line 653

**Comment by zachyarid** [comment]
And this is in the Auth class, correct?

**Comment by Conver** [comment]
Correct

**Comment by zachyarid** [comment]
```
if($this->config->smtp) {
			$mail->isSMTP();
			$mail->Host = $this->config->smtp_host;
			if(!is_null($this->config->smtp_auth)) {
			$mail->Username = $this->config->smtp_username;
			$mail->Password = $this->config->smtp_password;
			}
			$mail->SMTPAuth = $this->config->smtp_auth;
			$mail->Username = $this->config->smtp_username;
			$mail->Password = $this->config->smtp_password;
			$mail->Port = $this->config->smtp_port;

			if($this->config->smtp_security != NULL) {
				$mail->SMTPSecure = $this->config->smtp_security;
			}
		}
```

This is what it looks like now.

Unfortunately, it is still showing the same error.

**Comment by Conver** [comment]
You have             
$mail->SMTPAuth = $this->config->smtp_auth;
$mail->Username = $this->config->smtp_username;
 $mail->Password = $this->config->smtp_password;

two places, remove the last ones.

**Comment by Conver** [comment]
I'm going to update the class now.

**Comment by Conver** [comment]
Updated, if it still doesn't work for you.

Try add:
$mail->SMTPDebug = 2
to  line 648

**Comment by zachyarid** [comment]
None of this seemed to work either.

I'm gonna clear the class and redownload the new one you uploaded.

I'm getting ready to leave town for the day but I will keep you posted when I get around to doing it later tonight.
Thanks!

**Comment by cuonic** [comment]
Error #10 is strictly related to the email not being sent correctly, which is a result of incorrect SMTP parameters, which is not directly a problem with PHPAuth but [PHPMailer](https://github.com/PHPMailer/PHPMailer). 

Taking a look at documentation related to `ssrc.reachmail.net`, available [here](http://www.easy-smtp.com/smtp) it appears that authentication is required using a username and password.

I would recommend taking a look here: https://github.com/PHPMailer/PHPMailer/wiki/Troubleshooting

**Comment by zachyarid** [comment]
I'm still have the issue even after I replaced the updated files.

How can I test PHPMailer within PHPAuth?

**Comment by cuonic** [comment]
The updated files will not solve your problem. You can test PHPMailer by creating a file called `test.php` and using the following code:

    <?php

	require 'PHPMailer/PHPMailerAutoload.php';

	$mail = new PHPMailer;

	// Enable debug output
	$mail->SMTPDebug = 3;

	// Tell the mailer to use SMTP
	$mail->isSMTP();

	// Information based on the following documentation ttp://www.easy-smtp.com/smtp
	$mail->Host = 'ssrc.reachmail.net';
	$mail->SMTPAuth = true;
	$mail->Username = 'YOUR_SMTP_USERNAME';
	$mail->Password = 'YOUR_SMTP_PASSWORD';
	$mail->SMTPSecure = 'tls';
	$mail->Port = 587;

	// Set the from address
	$mail->From = 'no-reply@YOUR_DOMAIN.TLD';
	$mail->FromName = 'Test Mailer';

	// Set the to address
	$mail->addAddress('YOUR@EMAIL_ADDRESS.TLD');

	// Set the message subject
	$mail->Subject = 'Test Email';

	// Set the message body
	$mail->Body = 'This is a test email';

	// Attempt to send the email
	if(!$mail->send()) {
		// Something went wrong
		echo "[ERROR] Error encountered sending message.<br/>";
		echo "Mailer error: " . $mail->ErrorInfo;
	} else {
		// Message sent successfully !
		echo "[SUCCESS] Message sent."
	}

	?>
