### ISSUE TITLE
difference between two language error messages

### ISSUE THREAD

**Issue by KarelWintersky** [PHPAuth/PHPAuth#69]
What is differences between `Email address / password are invalid.` and `Email address / password are incorrect.`?

**Comment by cuonic** [comment]
[Invalid](http://www.urbandictionary.com/define.php?term=Invalid) means that it does not respect the required format (not a correct email address, too short, too long...)

[Incorrect](http://www.urbandictionary.com/define.php?term=incorrect) means that the email address could not be found in the database, or the password is not the correct one for that email address.
