### ISSUE TITLE
what about adding namespace PHPAuth like this:

### ISSUE THREAD

**Issue by KarelWintersky** [PHPAuth/PHPAuth#73]
What about adding namespace PHPAuth ?

```
namespace PHPAuth;
class Auth {...}
```

```
namespace PHPAuth;
class Config {...}
```

and 
```
$config = new PHPAuth\Config($dbh);
$auth = new PHPAuth\Auth($dbh, $config, $lang);
```
and so on...
I used this solution in my fork and all ok ;-)

**Comment by Conver** [comment]
PHPAuth used namespace in some of its first releases. We removed it, as we didn't see a good reason for it to be there.

Why do you want it there, what do you gain from it?
- Let me know, and I'll add it again if so.

cheers.

**Comment by KarelWintersky** [comment]
i think, this code is more useful:
```
$config = new PHPAuth\Config($dbh);
$auth   = new PHPAuth\Auth($dbh, $config, $lang);
```

In my project I have another Config class, that will conflict with PHPAuth\Config class. 

Of course, I can wrote something like 
```
$my_config = new MyOwnProject\Config($dbh);
...
$phpauth_config = Config($dbh);
```
But it is not so.. beautiful, because PHPAuth is third-party library and must use her own namespace.

**Comment by Conver** [comment]
That's correct. I'll reconsider it and add it later.

**Comment by KarelWintersky** [comment]
I can add it myself :)

Will be looks like this:
https://github.com/KarelWintersky/kwLiveMap/blob/master/backend/phpauth/config.class.php
https://github.com/KarelWintersky/kwLiveMap/blob/master/backend/phpauth/auth.class.php

**Comment by Conver** [comment]
hehe, dont worry. I know how it works.

**Comment by Conver** [comment]
fell free to submit PR :)
