### ISSUE TITLE
A system error has been encountered. Please try again. #04

### ISSUE THREAD

**Issue by linkin85** [PHPAuth/PHPAuth#74]
Fresh install, leads to this error when I register a new user.
I can't figure out what the problem is at all.
Code used:

$return = $auth->register("aabbccddee123@gmail.com","Sdfsfsd1","Sdfsfsd1");
if($return['error']) {
echo '<div style="color:red;"class="error">' . $return['message'] . '</div>';
exit();
}

**Comment by cuonic** [comment]
https://github.com/PHPAuth/PHPAuth/wiki/System-error-codes

#04 -> (addUser) Failed to update new user row in user table

You sure the database is set up correctly ?

**Comment by linkin85** [comment]
absolutely, as per supplied SQL file.

**Comment by linkin85** [comment]
Hi, I just wanted to give some further information. I compared the code from a previous version in july. when I changed it to this, it works:


		$customParamsQueryArray = Array();

		foreach($params as $paramKey => $paramValue) {
			$customParamsQueryArray[] = array('value' => $paramKey . ' = ?');
		}

		$setParams = ', ' . implode(', ', array_map(function ($entry) {
			return $entry['value'];
		}, $customParamsQueryArray));

		$query = $this->dbh->prepare("UPDATE {$this->config->table_users} SET email = ?, password = ?" . $setParams . " WHERE id = ?");

		$bindParams = array_values(array_merge(array($email, $password), $params, array($uid)));

		if(!$query->execute($bindParams)) {




to this 



		$query = $this->dbh->prepare("UPDATE {$this->config->table_users} SET email = ?, password = ? WHERE id = ?");
		if(!$query->execute(array($email, $password, $uid))) {




I guess there is a bug in that code somewhere with custom parameters?

**Comment by linkin85** [comment]
Sorry I have more concerns. I couldn't find anywhere on the current release where the cookie or session is set.
when I login, no cookie or session cookie is being stored at all.

**Comment by Conver** [comment]
Let me just debug this. will reply back soon.

**Comment by Conver** [comment]
Should be working again. Please report back.

**Comment by linkin85** [comment]
registration works perfectly, many thanks for that.
However, still no cookie being set when logging in.

**Comment by Conver** [comment]
This correct, debugging.. hang on :)

**Comment by Conver** [comment]
Please refer to: https://github.com/PHPAuth/PHPAuth/wiki/Class-Methods#login

Description:
Authenticates a user with the system. Note: You need to take the returned session hash and create the session cookie, the method does not do this for you.

**Comment by linkin85** [comment]
$return = $auth->login("example@gmail.com","Examplepassword", 1);

session_start();
$_SESSION["authID"]=$return['hash'];

is this an acceptable usage?
I'm slightly confused by this method? would you given an example of how to store hash into a session please?

**Comment by Conver** [comment]
You can use either session or cookies, I'd prefer cookies.

```php
if(!isset($_COOKIE[$cookie_name])) {
	$logged = false;
} else {
	if($auth->checkSession($_COOKIE[$cookie_name])) {
		$logged = true;
        $user = $auth->getUser($auth->getSessionUID($_COOKIE[$cookie_name]));
	} else {
		$logged = false;
		setcookie($config->cookie_name, "", time() - 3600, $config->cookie_path, $config->cookie_domain, $config->cookie_secure, $config->cookie_http);
	}
}
```
Quick example to check if logged in, not tested. But should give you and idea.

```php
$call = $auth->login($_POST['username'], $_POST['password'], $_POST['remember']);

if($call['error'] == 0) {
	setcookie($config->cookie_name, $call['hash'], $call['expire'], $config->cookie_path, $config->cookie_domain, $config->cookie_secure, $config->cookie_http);
}
```
Quick example to login, not tested. But should give you and idea.

**Comment by Conver** [comment]
You can use the new isLogged function aswell..
