### ISSUE TITLE
In my next commits ending ?> tags will be removed.

### ISSUE THREAD

**Issue by KarelWintersky** [PHPAuth/PHPAuth#75]
Reason: http://php.net/manual/en/language.basic-syntax.phptags.php

*If a file is pure PHP code, it is preferable to omit the PHP closing tag at the end of the file. This prevents accidental whitespace or new lines being added after the PHP closing tag, which may cause unwanted effects because PHP will start output buffering when there is no intention from the programmer to send any output at that point in the script*

**Comment by Conver** [comment]
They will already be removed. We are aware of this. thanks.
