### ISSUE TITLE
Plugin class

### ISSUE THREAD

**Issue by Conver** [PHPAuth/PHPAuth#87]
It would be great with some kind of "plugin" system, so we can create extra classes which can be loaded, example could be an Two-factor Authentication plugin class.

Please come with suggestion how we could create this the best and simplest way.

**Comment by Conver** [comment]
An row in config table could contain an array of plugins in JSON format etc. Would be an empty array at start.
And that way de/activate plugins?

______

Some kind of auto loader function, which checks a "plugin" folder within PHPAuth, and checks for class files and loads them if so.

**Comment by Conver** [comment]
@KarelWintersky, you have any idea for this?

**Comment by KarelWintersky** [comment]
Not so quickly ;-)

**Comment by mooztik** [comment]
i ve started an ambryon of this to test some group plugin experimentation.
tried with array of plugin names and autoload formated files from folders.
not so easy !! :)
not satified with the result.

i put here what i have recovered from trashbin :)

```php
class AuthPlugin extends Auth
{
 		
	private $dbh;
    public $config;	
	public $lang;
	public $about;
	
   /*
    * Initiates database connection
    * replace phpauth constructor
    * link to parent class
    */
   
	public function __construct(\PDO $dbh, $config, $lang)
    {
    	parent::__construct($dbh, $config, $lang);
		$this->config = $config;
        $this->dbh = $dbh;
		$this->lang = $lang;

		//$this->PG = new
		$this->PG_load($this->PG_list());
		
		var_dump($this->PG->about);
    }

	/**
	 * list all plugins from plugin folder 
	 */
	 
	private function PG_list()
	{
		$directory = __DIR__.'/plugins';
		$dirs = scandir($directory);
		unset($dirs[0], $dirs[1]);  // delete folder dots
				
		foreach($dirs as $id => $file)
		{			
			if(is_dir($directory.'/'.$file)) {
				if(!file_exists($directory.'/'.$file.'/loader.php')) { unset($dirs[$id]); } // ignore folders without loader.php file
			} else { unset($dirs[$id]); }
		}
		return $dirs;
	}

	
	
	/**
	 *  Load the plugins
	 * build it this way for use :  $auth->PG->__plugin-name__->function()
	 */

	private function PG_load($dirs)
	{
		$directory = __DIR__.'/plugins';
		
		if(!isset($this->PG)) {
			$this->PG = new stdClass();
		}
		
		
		foreach($dirs as $dir)
		{
			include_once($directory.'/'.$dir.'/loader.php');
			
			if(!class_exists($dir))
			{
				trigger_error($this->lang['PG_plugin_load_error'], E_USER_WARNING);
			}
			
			$this->PG->$dir = new $dir($this->dbh, $this->config, $this->lang);			
			$this->PG->about[$dir] = $this->PG->$dir->about = $this->PG_about($dir, $directory);
		}
		
		
		
	}
	
	
	private function PG_about($dir, $directory)
	{
		//get info from each plugin
			$file = $directory . '/'.$dir.'/about.txt';
			$handle = fopen($file, "r");
			$raw = fread($handle, filesize($file));
			fclose($handle);
			
			$lines = explode("\n", $raw);
			foreach($lines as $line)
			{
				$tmp = explode('=', $line);
				$data[$tmp[0]] = $tmp[1];				
			}
		return $data;
	}
	
	
	
	private function PG_assign()
	{
		
		
	}
 }
```

**Comment by JacquesLoubser** [comment]
Why not add such features to the Base code, or as an additional class: phpauth.extend.class.php?

I am currently adding some features in for a project I am working on (more advanced attack mitigation, Google recaptcha, group policy / shared data)

**Comment by KarelWintersky** [comment]
IMHO, adding features to Base code is not a good idea. 
Additional class is little better. A little.

Scan plugins dir is better idea.

**Comment by JacquesLoubser** [comment]
Maintenance-wise agreed, but adding captcha and otp requires changes to the isBlocked() and login() methods. How would you do that with a plugin?

**Comment by mooztik** [comment]
by adding 'rules' inside these methods.
rules can be set from outside(child plugins class), and used (if defined) in isBlocked() and login() methods.

it's a pure theorical idea. i m digging it ! :)

**Comment by Conver** [comment]
You can also override functions within child classes

**Comment by mooztik** [comment]
rewriten a little my previous trash code.
now works perfectly
plugins are loaded dynamicly from plugin/ directory 
the plugin directory is scanned and all found plugins are loaded
class are defined and directly usable
i have added a child namespace for theses plugins :  namespace PHPAuth\plugins
```php
<?php
namespace PHPAuth;
class AuthPlugins extends Auth
{
 		
	private $dbh;
    public $config;	
	public $lang;
	public $about;
	public $plugin;
	
   /**
    * Initiates database connection
    * replace phpauth constructor
    * link to parent class
    */   
	public function __construct(\PDO $dbh, $config, $lang)
    {
    	parent::__construct($dbh, $config, $lang);
		$this->config = $config;
        $this->dbh = $dbh;
		$this->lang = $lang;
		
		$this->PG_load($this->PG_list());
    }

	/**
	 * list all plugins from plugin folder
	 * 
	 */	 
	private function PG_list()
	{
		$directory = __DIR__.'/plugins';
		$dirs = scandir($directory);
		unset($dirs[0], $dirs[1]);  // delete folder dots
				
		foreach($dirs as $id => $file)
		{			
			if(is_dir($directory.'/'.$file)) {
				if(!file_exists($directory.'/'.$file.'/loader.php')) { unset($dirs[$id]); } // ignore folders without plugin.php file
			} else { unset($dirs[$id]); }
		}
		return $dirs;
	}

	
	
	/**
	 *  Load the plugins
	 * build it this way for use :  $auth->__plugin-name__->function()
	 * @param array $dirs
	 */
	private function PG_load($dirs)
	{
		$directory = __DIR__.'/plugins';		
		
		foreach($dirs as $dir)
		{
			include_once($directory.'/'.$dir.'/loader.php');			
			
			$cname = 'PHPAuth\plugins\\'.$dir;
			$this->$dir = new $cname($this->dbh, $this->config, $this->lang);			
			$this->plugin[$dir] = $this->$dir->about = $this->PG_about($dir, $directory);
		}		
	}
	
	
	/**
	 * load text file containing plugin infos
	 * used text file to simplify information access
	 * perhaps not the better way, but simple enough for actual needs
	 * @param string $dir
	 * @param string $directory
	 */
	private function PG_about($dir, $directory)
	{
		//get info from each plugin
		$file = $directory . '/'.$dir.'/about.txt';
		$handle = fopen($file, "r");
		$raw = fread($handle, filesize($file));
		fclose($handle);
		
		$lines = explode("\n", $raw);
		foreach($lines as $line)
		{
			$tmp = explode('=', $line);
			$data[$tmp[0]] = $tmp[1];				
		}
		return $data;
	}	
 }
```
now an exemple of a group plugin set in **PHPAuth/plugins/groups** folder

```php
<?php
namespace PHPAuth\plugins;

/**
 * Group plugin for PHPAuth
 */

class groups
{
	private $dbh;
	public $config;
	public $lang;
	public $about;
	
	
	public function __construct(\PDO $dbh, $config, $lang)
	{
		$this->dbh = $dbh;
		$this->config = $config;
		$this->lang = $lang;
	}
		
	
	/**
	 * check if user is in this group
	 * @param int $gid : group id
	 * @return boolean
	 */	 
	/**
	 * check if user is in this group
	 * @param int $gid : group id
	 * @param int $uid : user id
	 * @return boolean
	 */	 
	public function checkAuthGroup($gid,$uid)
	{
		//prepare query
		$query = $this->dbh->prepare("SELECT uid FROM {$this->config->table_usergroups} WHERE gid = ? AND uid = ?");
        $query->execute(array($gid, $uid));

        if ($query->rowCount() == 0) {
            return false;
        } else {
        	return true;
		}
	}
 ... and other methods...
}
```
now you can call **$auth->groups->checkAUthGroup($groupID)**

**Comment by Conver** [comment]
Nice one @mooztik, would you make a PR for it? and maybe add the example to the readme?

**Comment by mooztik** [comment]
some questions.
about plugin supporty integration : is the plugin support h

**Comment by KarelWintersky** [comment]
I think so:
> is the plugin support have to be 

A secondary class extending auth class `class AuthPlugin extends Auth` 
Implementing plugins inside `Auth` class or as subclass can (and will!) dramatically increase complexity of current code. 

> plugins loading : do they need to be loaded ..

Manually! From config array or declaration like `new PHPAuth\Plugin(['plugin1', 'plugin2'])`

> plugin(s) installation/ db needs

providing .sql file and let admin do all work. No any automation actions, please. 

> plungin(s) installation/ config needs

load configuration from `.json`-file may be useful. On the flipside, custom plugin table is more useful. 

If plugin does not save any data - static config is useful.

**Comment by Conver** [comment]
> plugins loading : do they need to be loaded ..

> Manually! From config array or declaration like new PHPAuth\Plugin(['plugin1', 'plugin2'])

Autoloader function. Like php itself does it. 

```php
spl_autoload_register(function ($class){
    include("inc/classes/{$class}.php");
});
```

then it only loaded if the function is called

**Comment by mooztik** [comment]
there's so many things to take into account than i'm a little bit lost.
tested : 
-autoload -> in case of plugins doing the same thing (for exemple a simple captcha & evolved captcha) all classes are listed.. no really necessary. and how to use the right class in phpauth main library ?

- subclasses -> the way i was doing things. to strict! missing simplicity and reusability

- extend auth class and overwrite methods -> same has subclasses, missing simplicity.

then, the way i'm exploring things now are external classes usable by PHPAuth using listed plugins in config table.
for exemple, `$config['plugin_captacha'] = 'mycaptcha'; `
then when PHPAuth call it's internal captcha method, this one check the config and use the plugin handler to check if the corresponding class is loaded (load it if necessary) and execute the captcha request and wait for the result.
where i m now is to find the best way to integrate things from outside PHPAuth, because the main interest in this plugin system is using existing libraries (like captcha, recaptcha...)
but where i'm a bit lost is in how to know what method to use (each library have it's own method names)....

**Comment by livmackintosh** [comment]
You could make use of composer now :smile: each plugin can just be a dependency of someones project? If you choose to use composer, plugins can have a custom package type so they are stored in the plugins folder? 

Not sure about architecture of plugins but @mooztik has some ideas. :smiley_cat: 

Liv

**Comment by mooztik** [comment]
first shot
i have chosen to set plugin methods directly inside phpauth main class.
finally the method is so small that it not requires any external file

methods created and captcha as exemple
https://gist.github.com/mooztik/e9951032e1e7c4143137#file-onlyplugincode-phpauth-class-php

**Comment by mooztik** [comment]
first working exemple
https://github.com/mooztik/PHPAuth
moved extra userdata informations to a plugin and moved data to a specific sql table
moved recaptcha code to recapcha plugin
an embryo of group support (not working yet)

temporary using class extend to not touch current phpauth code

**Comment by Conver** [comment]
status?
