### ISSUE TITLE
language from auth

### ISSUE THREAD

**Issue by Conver** [PHPAuth/PHPAuth#91]
Should we include the language file within the auth class at  `__construct`?

We can go both ways, either its language specific for PHPAuth and should be included within the file.
Or its system language file, and it continues to be included as of now, but then it require people to base their whole language system on ours, which I'm not the biggest fan of since we ain't trying to limit people, but give them better options.

----------
I'm just doing like this in some of my systems.
```php
	public function __construct(\PDO $dbh, $config)
	{
		$this->dbh = $dbh;
		$this->config = $config;
  
        require("inc/languages/{$this->config->site_language}.php");
		$this->lang = $lang;

		if (version_compare(phpversion(), '5.5.0', '<')) {
			require("inc/files/password.php");
		}
	}
```
Then, if `site_language` isn't defined, then it could just fall back to default language, which would be `en_GB`
```php
$this->config->site_language = (is_null($this->config->site_language)) ? 'en_GB' : $this->config->site_language;
        
require("inc/languages/{$this->config->site_language}.php");
$this->lang = $lang;
```
---------
Let me know what you all think about this?

**Comment by Conver** [comment]
See #89 aswell for more about language files.. #89 is also added to the todo list

**Comment by mooztik** [comment]
i repeat what i say previously.
i m using HTTP_ACCEPT_LANGUAGE, the way phpauth actually support multi language satisfy me.
adding the possibility to support more language files/systems (like json, gettext, text files..) is more accurate than fixing one and only format.
i think phpauth need to keep flexibility, need to be implemented and run easely, with minimum requierements and adaptation.
