### ISSUE TITLE
PHPAuth\Auth->getUser() invalid description... and implementation

### ISSUE THREAD

**Issue by KarelWintersky** [PHPAuth/PHPAuth#93]
https://github.com/PHPAuth/PHPAuth/commit/2ea7999163af25f5d3fc37380f91e9206c04e8de

Added ability to add additional profile fields in the registration, but getUser() returns only old fields. 

Also, user's salt not exists.

**Comment by Conver** [comment]
Fixing in a few  minutes.

**Comment by mooztik** [comment]
about this.
is this not better to not return password outside the class, and propose a specific method to return user data without sensible data ?

**Comment by KarelWintersky** [comment]
@mooztik you are right. 
Something like:

```
public function getUser($uid)
	{
		$query = $this->dbh->prepare("SELECT * FROM {$this->config->table_users} WHERE id = ?");
		$query->execute(array($uid));

		if ($query->rowCount() == 0) {
			return false;
		}

		$data = $query->fetch(\PDO::FETCH_ASSOC);

		if (!$data) {
			return false;
		}
unset($data['password']); 

		$data['uid'] = $uid;
		return $data;
	}
```

**Comment by mooztik** [comment]
i've made this already :)
but built another method.
i passed the original method to private (internal use only, who do not need extra fields),
and using a public userData($uid) method to obtain all fields exept password

**Comment by mooztik** [comment]
i didn't see any cleaning/security check for extended parameters.
not even an htmlentites ?!
am i wrong ?

**Comment by bugada** [comment]
I like the @mooztik approach, can we proceed?

**Comment by Conver** [comment]
Please proceed.

**Comment by bugada** [comment]
#117 fixes the getUser() bug, Please check that is ok and close the issue.
Thank you.
